### ISSUE TITLE
Chrome 50 and 51 doesn't have the ImageBitmap.close() method

### ISSUE THREAD

**Issue by edotassi** [nodeca/pica#100]
Chrome 50 and 51 has only basic support for ImageBitmap (https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap). 
Method `close()` was implemented since Chrome 52.

**Comment by puzrin** [comment]
Ok, i'll update cib feature detection, later...

Anyway, cib is not useable, see #89

**Comment by edotassi** [comment]
Ok...
Why my cordova app running inside Chrome 51 invoked `ImageBitmap.close()` if cib isn't enabled?

**Comment by puzrin** [comment]
You are right. There is a second use-case for ImageBitmap - optimized jpeg extraction. It's used even if resize not supported.

Will fix ASAP. Thanks for report.

**Comment by puzrin** [comment]
Released 3.0.6. Let me know if problem still exists or solved.

**Comment by edotassi** [comment]
Thanks for the quick reply, now i have updated Chrome to version 59 on the emulator.
As soon as i'll try.
