### ISSUE TITLE
Support Different Dimensions than Destination

### ISSUE THREAD

**Issue by darkfrog26** [nodeca/pica#102]
Currently, Pica only supports resizing to the size of the destination canvas. However, it is often useful to draw on an existing canvas but at a specific size and position.

**Comment by puzrin** [comment]
My general approach is to keep api simple. So, need proofs why your use case is popular. Nobody asked that before.

**Comment by puzrin** [comment]
Can we close this? Canvas create/copy is cheap anyway.
