### ISSUE TITLE
Resize result blurry

### ISSUE THREAD

**Issue by Christilut** [nodeca/pica#103]
I'm trying to reduce the size of files before I send them to S3 (in my test case a 5MB .jpg file).

A user can select a file through an `<input type="file">` element, then a FileReader puts the data in a `<img>` element. My target `<canvas>` gets the height/width of the previous img.
The img and canvas are then fed into Pica and on the result I do `.toBlob()`

I would expect that the resulting .png image is of the same resolution as the source but in my test case it has a resolution of 300x150 and the source is 4288x2848

Am I doing something wrong here?
(the timeouts in code below are just for development and should be replaced)
```js
          const reader = new FileReader()

          reader.onload = async (event) => {
            this.$refs.image.src = event.target.result

            setTimeout(async () => {
              this.$refs.canvas.style.height = this.$refs.image.clientHeight + 'px'
              this.$refs.canvas.style.width = this.$refs.image.clientWidth + 'px'

              setTimeout(async () => {
                const res = await Pica.resize(this.$refs.image, this.$refs.canvas, {
                  unsharpAmount: 80,
                  unsharpRadius: 0.6,
                  unsharpThreshold: 2
                })

                res.toBlob(async (blob) => {
                  await this.$store.dispatch('website/uploadFile', {
                    file: blob
                  })

                  this.$store.commit('notifications/add', {
                    message: 'Upload complete'
                  })
                }, 1000);

              })
            }, 1000)
          }

          reader.readAsDataURL(file)
```

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/3.0.6/index.js#L257-L260

See how pica creates canvas of desired size.
