### ISSUE TITLE
File support [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [nodeca/pica#104]
Is it possible to add `File` support to methods instead of using canvas elements (as well as having a `Blob` binary output)?
This would be very handy as most of us are getting the image to modify as a `File` object from a `input[type=file]`.
This way this library will be the ultimate solution to `image processing` client side 😄

**Comment by puzrin** [comment]
No, file is upper abstraction layer. `pica` is designed to consume bitmaps (decoded images). IMHO it's not good idea to mix different layers in api. Also file may need additional processing (orientation extract, for example)

You can dig this src https://github.com/nodeca/nodeca.users/blob/master/client/users/uploader/uploader.js to get more ideas about files processing.

**Comment by damianobarbati** [comment]
@puzrin allowing Pica to accept blobl/binaries would make it much more abstract then it now.
Requiring canvas/img elements is troublesome: 
- since the goal is browser/client file processing 
- since users upload files through "file[type=upload]"
- you are forcing developers to display the vanilla image someway (even if hidden in the dom) using <img/> or <canvas/> when probably developer wants to use Pica first to resize them (why using otherwise?)

Typical scenario: 
- users upload a bunch of images (nowadays 2k or 4k)
- developers must create canvas or image elements with the uploaded files (useless duplication of files in memory here? With pica internal toBlob() we have a x3 memory footprint for each image - FileUpload + Canvas bitmap + toBlob? - not nice on mobile)
- developers use pica to resize them
- developers display resized item on another canvas / img elements
- developers must convert those elements to binary (how do you upload them otherwise?)
- developers have to clean up the mess and proceed with wanted logic

Best scenario:
- users upload a bunch of images (nowadays 2k or 4k)
- developers use FileReader to compute the blob/binary and pass it to pica
- developers use pica to resize them
- developers use pica converted binaries as they prefer proceeding with wanted logic

**Comment by puzrin** [comment]
That's a many beautiful words, without one small detail... How do you suggest to extract binary data + orientation from blob without canvas?

**Comment by damianobarbati** [comment]
You can either use `exif-js` (https://github.com/exif-js/exif-js/blob/master/exif.js#L1003) or something like http://jsfiddle.net/3pnvjupj/.
I've personally dropped the latter in favour of the former.
Up to the dev I guess.
But this would free Pica (and devs) from the burden of canvas where not needed 🙂

**Comment by grahams** [comment]
Not every file is a JPEG nor does every file have an EXIF header.

**Comment by puzrin** [comment]
You did not answered, how do you plan to extract image data from blob.

**Comment by damianobarbati** [comment]
@puzrin something like

```
const getBinary = file => {
    return new Promise((resolve, reject) => {
        const fileReader = new FileReader();
        fileReader.readAsArrayBuffer(file);
        fileReader.onload = () => resolve(new Uint8Array(fileReader.result));
        fileReader.onerror = error => reject(error);
    });    
};

input.onchange = async event => {
    const binary = await getBinary(input.files[0]);
    console.log(binary.length);
};
```

Quick fiddle http://jsfiddle.net/3pnvjupj/2/ as example

**Comment by damianobarbati** [comment]
@grahams both Android and iOS cameras use JPEG format and that's where you need to check orientation thus problem solved. 
Which other use case otherwise? 🤔

**Comment by puzrin** [comment]
@damianobarbati your example does not unpack jpeg. That's not not correct replacement.

I'd suggest you to investigate carefully code, refered in my first reply. Because you need better understanding about difference between blobs resize and canvas resize. In other words, as i said, your suggestion does not match this project scope.

**Comment by grahams** [comment]
@damianobarbati Are you really suggesting that the only thing people would like to scale are images that came from the camera apps from iOS or Android devices?

What about PNGs?  GIFs?  What about non-pictures such as scanned text documents?  In fact, I'd argue that using pica is more useful when scaling scanned text than it is with pictures (since the interpolation built into the browsers is so bad).

We use pica here:  http://html5.snowbound.com/  The DOC and PDF files are rendered to SVG on the server (and therefore we don't use pica on them), but the TIFF and JPEG files are scaled via pica.

**Comment by damianobarbati** [comment]
@grahams totally correct, I never thought about scanned documents

**Comment by damianobarbati** [comment]
@puzrin I'm sorry then because I don't think I get it: I thought behind the scenes all Pica does with provided canvas is 1) extracting binaries to process on first canvas 2) display result back on second canvas.
I'm missing something here, closing this to not waste your time guys :)

**Comment by puzrin** [comment]
Pica works with raw bitmaps, with some sugar. Extracting raw bitmaps from blobs is completely different story.

**Comment by Aarbel** [comment]
@damianobarbati have you found a synthetic way / library to resize images from inputs ?

**Comment by Aarbel** [comment]
Found this https://github.com/ericnograles/browser-image-resizer, absolutely perfect

**Comment by puzrin** [comment]
https://github.com/nodeca/image-blob-reduce - this is pica wrapper for files. With predictable quality.
