### ISSUE TITLE
"Can't find variable assign" in Safari

### ISSUE THREAD

**Issue by haf** [nodeca/pica#105]
<img width="925" alt="screen shot 2017-08-24 at 09 20 39" src="https://user-images.githubusercontent.com/193115/29654443-89995c70-88ad-11e7-883b-fac222b1de4f.png">

Repro: load a site that uses Pica in Safari.

**Comment by puzrin** [comment]
You should use file from `/dist` folder or properly setup browserifier. Try to open demo in safary, it should work.

**Comment by haf** [comment]
Not webpack-compatible then, I suppose?

**Comment by puzrin** [comment]
https://github.com/nodeca/pica#install

Even if you manage to build it with webpack, webworkers will not work (not supported).
