### ISSUE TITLE
Support ImageBitmap and OffscreenCanvas

### ISSUE THREAD

**Issue by mnpenner** [nodeca/pica#107]
Basically, I want to do this:

```
self.createImageBitmap(file).then(image => {
    let fit = makeFit(image);
    const dest = new OffscreenCanvas(fit.width, fit.height);
    pica.resize(image, dest);
});
```

But pica doesn't seem to support [`ImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap) as a source, not [`OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) as a dest.

Basically I want to do this entirely in a web-worker and this is the only way I can think to do it.

Alternatively, a Blob, or [Object URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) would be useful destinations so that I can render this into a standard `<img>` instead of a canvas.

**Comment by puzrin** [comment]
You could extract bitmap yourself and use resizeBuffer. What are reasons to place pica to ww entirely? It already knows how to use ww for heavy math.

**Comment by mnpenner** [comment]
I'll take a look at `resizeBuffer`, thank you. I'm using my own WW because I'm doing some other processing anyway. I want to get my images off the main UI thread as quickly as possible so there are no hang ups.

**Comment by puzrin** [comment]
1. ImageBitmap is supported in latest browsers only.
2. Creating IB from file is not enougth, because you may need to tweak orientation.

Pica's advantage is that it's universal and restricted to it's responsibility area. It still has api (resizeBuffer) to easy create custom wrapper for advanced use, when specific requirements can not be included to upstream. I think if you dig sources, you will find enougth info to write your code as you need.

Also see https://github.com/nodeca/nodeca.users/blob/master/client/users/uploader/uploader.js how we process files, that's a separate task, not embeddable to pica.

**Comment by mnpenner** [comment]
Thanks for the tips.

I'm basically trying to move [all of this](https://github.com/nodeca/nodeca.users/blob/ddd4d40a9f94c8fe9b3dc232a71e9c9721152922/client/users/uploader/uploader.js#L84-L230) into the WW too. That runs plenty fast for one image, but I want to support uploading 100s of images at once. I've got it running pretty well now thanks to your source :smile:

**Comment by puzrin** [comment]
I would keep in WW math only (as pica does now), because other operations are not blocking. But nobody can prohibit you to experiment if you wish.

Note, that `resizeBuffer()` does not tile image to slices, that can cause more memory consumption on huge images.

**Comment by FarSeeing** [comment]
I know this issue is quite old but any plans to support `OffscreenCanvas` at least as input source?

**Comment by puzrin** [comment]
@FarSeeing could you explain what's wrong right now?

**Comment by FarSeeing** [comment]
@puzrin - it simply doesn't work: you use use `HTMLCanvasElement` instance as a source but cannot `OfflineCanvas` because of this check:
```javascript
module.exports.isCanvas = function isCanvas(element) {
  //return (element.nodeName && element.nodeName.toLowerCase() === 'canvas') ||
  let cname = objClass(element);

  return cname === '[object HTMLCanvasElement]'/* browser */ ||
         cname === '[object Canvas]'/* node-canvas */;
};
```

**Comment by puzrin** [comment]
If only one line in check should be added - i see no problem at all. That code was written when OffscreenCanvas not existed.

Could you test with added line `cname === '[object OffscreenCanvas]' ||` and tell me if that helps (or create PR)?

**Comment by FarSeeing** [comment]
Sent PR.
Using `OffscreenCanvas` instance as as target in `resize` method works "out of box". Added support for input in `resize` and `toBlob` methods.

**Comment by puzrin** [comment]
Released 5.2.0

**Comment by puzrin** [comment]
Seems found case when `ImageBimap()` input may be useful - in can be created directly from `Blob()`, without proxy `Image()` object.

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/commit/e948fcb3dd5f045fbbeb6f03782cc96b169ad0a9

**Comment by FarSeeing** [comment]
Just FYI - `OffscreenCanvas` prototype provides method [transferToImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/transferToImageBitmap)
I'm not sure that's better than current approach (`getContext` + `getImageData`) so just as an information.

**Comment by puzrin** [comment]
This feature is for input only, to skip old-style canvas load via `Image()`. 

Internally we still should have canvas <=> canvas transform, because it's the only way to get and put tiles of raw bytes.

I theory, it's possible to do that in webworkers, but i doubt this will give notable gain, and it certaintly will be ass pain to have variable data formats & feature detection for webworkers.

**Comment by FarSeeing** [comment]
Yes, I understand that's for the input. I meant that in case we use canvas instance we manipulate `ImageData` and do the same for `OffscreenCanvas` instance while potentially we can use that `transferToImageBitmap` method.
I'm super skeptical that it's better in terms of performance so just leaving a note that it's possible.

**Comment by puzrin** [comment]
Take a look at https://github.com/nodeca/pica/issues/194#issuecomment-640966863 please, if you have time. Seems you have good use cases about what is required to resize blobs.

After digging about how to add Chrome workaround to my apps, it seems separate package could be optimal solution. But i don't know if proposed api will be good enough for others. My use cases are very simple.
