### ISSUE TITLE
Production build problem when used with Angular

### ISSUE THREAD

**Issue by mordka** [nodeca/pica#110]
I had problems with using the library in the latest Angular (4.4.6). Probably because of webpack minifier plugin. I found a workaround and wanted to share.

### The problem
Prod build fails with the following error:
```
ERROR in vendor.93810be15b3d2ab6ffae.bundle.js from UglifyJs
Unexpected token: name (cname) [/home/user/pica/node_modules/pica/lib/utils.js:9,0][vendor.93810be15b3d2ab6ffae.bundle.js:15321,6]
```

### Steps to reproduce
1. ` ng create test && cd test && npm install -S pica`
2. app.compontent.ts:
```
import { Component } from '@angular/core';
import * as pica from 'pica';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  constructor() {
    pica();
  }
}
``` 
3. ng build --prod -sm

### Workaround
1. Add ` "allowJs": true,` to `compileOptions` in tsconfig.json
2. Import pica `import * as Pica from '../../node_modules/pica/dist/pica.min.js';`

Probably related: #106

**Comment by puzrin** [comment]
See [notes about browserify](https://github.com/nodeca/pica#install) or search "webpack" in issues/PRs. For example https://github.com/nodeca/pica/pull/109#issuecomment-337221973

I think, something like `import * as pica from 'pica/dist/pica.js'` should help

I do not object to improve things, but nobody yet suggested how to improve webpack work without breaking everything else. If you have ideas - let me know.

**Comment by puzrin** [comment]
As far as i remember, there exists some convention about separate es6 entry point in `package.json` But i don't know how stable is it and will it change in future or not. Need info from someone, who has experience with such situations.
