### ISSUE TITLE
[QUESTION] is pica a singleton?

### ISSUE THREAD

**Issue by asturur** [nodeca/pica#115]
I' m working on an application where i use pica often with many images at time.
I was on a part of the code where i resize all the images serially and i wanted to move the code in a sort of parallel with a promise.All from bluebird wrapping everything.

Since i m passing pica options and i have no guarantee of the order the resizes and the tiling will happen for each image, can i safely start 2 pica resize togheter?

```javascript
const pica = new Pica(PICA_SETTINGS);  // once

export default function myResize(image, { height, width }) {
  cost outputCanvas .... create a canvas....
  return pica.resize(image, outputCanvas, RESIZE_SETTINGS);
}
```

is the function `myResize` safe to be used in parallel since it use the same pica instance?

should i create more pica instance?

**Comment by puzrin** [comment]
If you use the same pica class instance, it's almost safe to run multiple resizes in parallel. They use the same worker pool (it will be a bottleneck). RAW memory consumption in pica should be will ~ (workers * tile size), about (4MB * workers, i don't count js engine spents here).

Workers are cached with small timeout, and creation delay will be on first run only (then worker will be reused if next tile run immediately).

But if you create multiple src canvases, you will spend memory for each (4 bytes * width * height). If your sources are huge, it's better to create canvas one-by-one, instead or running all in parallel. Peak memory spent depends not on pica (it's fixed there) but on source canvas.

**Comment by asturur** [comment]
i use lot of memory, i m just worried about overlapping settings.
Does a resize from 5000x5000 to 500x500 in parallel wit another that has different AR and scale ratio, could mix some internal setting?

**Comment by puzrin** [comment]
> i use lot of memory, i m just worried about overlapping settings.

AFAIK, you should not worry about this. You should worry about memory:

- src image 5000 * 5000 * 4 bytes =>100MB
- pica consumption on 8 workers will be 4mb*8 => 24mb max (+ js engines). That's fixed and will not grow.

So, if you try to resize 10 huge images in parallel, pica will allocate 24mb for internals, but your source images will take 1GB - that's not good.

**Comment by puzrin** [comment]
To be honest, pica will eat a bit more if you use unsharp mask. 4mb image + 2-4bm for internal buffers. But general idea is the same. Image is processed by "small" tiles, and memory consumption can not exceed some reasonable limit. Even if you run, multiple resizes, those will be ordered inside the same pica instance. The only "uncontrollable" param is source canvas.

**Comment by asturur** [comment]
Thanks for clarifying all those details. with my statement about memory I meant that memory occupation is something i can work on, when i decided if to take the serial or parallel approach. But i will not influence the decision from it.
Other than pica, the image get probably loaded on a canvas, plus the eventual dataurls and blobs i have around for caching reasons. Pica is just a part of the memory occupation.

Since after a resize start other processes, i have to weight costs and benefits generally.

**Comment by puzrin** [comment]
If you are sure your sources fit in memory, and use the same pica instance, it doesn't matter if you run resize in parallel or in waterfall.

The only advice is to not make > 2 sec pause between images - then workers will be reused. First worker init is expensive - you can play with demo to see difference. Click on top left image with small delay and with big delay to compare timing.

You can try to tune workers count or tile size, but i don't recommend to do so. Defaults should be good enougth. That may be useful for investigations only.

**Comment by asturur** [comment]
thank you very much for everything
