### ISSUE TITLE
I have a question: if I do not set the width

### ISSUE THREAD

**Issue by wytong123** [nodeca/pica#117]
in the demo：
`var updateResized = _.debounce(function () {
  var dst, ctx, width, start, time;
  width = 3600;`
If the width remains unchanged（same as the original image）, I use pica, just set the "quality" "unsharpAmount" "unsharpRadius" "unsharpThreshold", the size of the image can change how much， I use, the picture size only change a little，

`                       create_resizer();
                        var img = new Image();
                        img.src = e.target.result   
                        var dst, width, height;
                        width = towidth;
                        height = toheight;
                        dst = $('#dst-pica')[0];
                        dst.width = width || (img.width * height / img.height);
                        dst.height = height || (img.height * width / img.width);
                        var offScreenCanvas = document.createElement('canvas')
                        offScreenCanvas.width = dst.width;
                        offScreenCanvas.height = dst.height;
                        resizer.resize(img, offScreenCanvas, {
                                quality: 0,
                                alpha:false,
                                unsharpAmount:100,
                                unsharpRadius:2,
                                unsharpThreshold:0,
                                transferable: true
                            })
                            .then(function() {
                                // dst.getContext('2d').drawImage(offScreenCanvas, 0,0);
                                var resizeimage = offScreenCanvas.toDataURL("image/png");
                                $.wwclass.helper.updateProp($ele, "data-x-imgsrc", resizeimage);
                                var input = e.currentTarget;
                                input.value = '';
                                // 延后执行, 以便让data-x的同步先进行处理
                                setTimeout(function() {
                                    $.wwclass.helper.anijsTrigger($ele, "getimg");
                                }, 0);
                            })`

**Comment by puzrin** [comment]
Pica should work when size remains the same.  But if you need unsharp mask only, it's probably better to call unsharp mask implementation directly in https://github.com/nodeca/multimath
