### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by leoliu** [nodeca/pica#119]
I am using pica to resize images in the browser and it produces very good result. however I can only run it in development. Ideas?

```
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/pica/lib/mathlib.js:19 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by puzrin** [comment]
No ideas about your minifier. IMHO this question is not for this tracker. Try to use pre-build files: https://github.com/nodeca/pica/tree/master/dist

**Comment by leoliu** [comment]
I am using it with create-react-app + "react-scripts": "1.0.17" without any customisations. I have tried using those in dist/ but could not load them either. Moving them to src/ didn't help.

**Comment by puzrin** [comment]
I don't use react and not familiar with their instruments. But as you can see, this project minify itself with success and standalone script works.

**Comment by ykshev** [comment]
@leoliu I have the same issue. Did you find a solution?

**Comment by leoliu** [comment]
@ykshev,

No, I have no solution yet. Since it causes the project to fail to build, I have to back out the lib for now.

Leo

**Comment by afrad** [comment]
you can import the mignified file directly:
import pica from 'pica/dist/pica.min'
that would solve the problem
