### ISSUE TITLE
Add callback for progress information

### ISSUE THREAD

**Issue by tpetry** [nodeca/pica#120]
If you want to resize some 4k or 8k images you have to wait a looong time (~30s). It would be really nice to add a progress callback to the options for getting some (inaccurate) progress information.

Could look like this:
```js
pica().resize(image, canvas, { progress: (percent) => $('#progressResize').css('width', percent * 140) })
   .then(canvas => $('body').append(canvas))
```

**Comment by puzrin** [comment]
No principal objections, but with a bit different option:

```js
{
  onProgress: function (stat) { ... }
  // stat => { complete, total } tiles count, may be arrays
}
```

Percent is too artificial, expected to be precise, and is not extendable.

**Comment by puzrin** [comment]
After starting implementation - found unexpected problem. Pica can do resize in multiple passes https://github.com/nodeca/pica/blob/master/lib/stepper.js. So, no idea how to create universal result.

**Comment by puzrin** [comment]
Closing - outdated.
