### ISSUE TITLE
Resizing without blocking the ui?

### ISSUE THREAD

**Issue by tpetry** [nodeca/pica#121]
Is there some way to use pica for resizing images without blocking the window context? If i use for example [this insanely large image (11658 × 6112)](https://www.desktopbackground.org/wallpaper/top-viewed-wallpapers-873526) the resizing takes  some seconds on slow mobile devices.

I tried already:
* using only `ww` for allowed features but the MathLib does not allow selecting only `ww`without `js` or `wasm`
* using [canvas-webworker](https://github.com/casperlamboo/canvas-webworker) to emulate `Image` and `Canvas` within a web worker context but there are many operation within pica which will access functionality only available within the window context

**Comment by puzrin** [comment]
Just use pica in modern browser, and webworkers will be used automatically, without blocking. Could you explain what's them problem with?

**Comment by tpetry** [comment]
I am not able to reproduce it anymore. Some device did block the ui with one of the test images, but i can't find the combination anymore.
