### ISSUE TITLE
IOS 10.2.2 Error: Out of bounds memory access

### ISSUE THREAD

**Issue by aurimasniekis** [nodeca/pica#124]
After the iOS 11.2.2 update released Jan 8th 2018 the library is now failing to operate properly, and is throwing the error shown below. It was tested in both the native safari browser and in a web view embedded in an application on device against the sample application in this repo. Any thoughts?

    IOS 10.2.2 Error: Out of bounds memory access (evaluating '(E.exports.convolveHV||E.exports._convolveHV)(w,B,p,i,n,a,s)')

I think is is related to this: https://github.com/kripken/emscripten/issues/6042

**Comment by puzrin** [comment]
Thanks for info. I think, it worth to wait until iOS fixed? Or you can manually disable wasm at all.

**Comment by aurimasniekis** [comment]
I don't there is something to be fixed, it's WebKit new policy to not allow out of bound access on arrays

https://webkit.org/blog/8048/what-spectre-and-meltdown-mean-for-webkit/

**Comment by puzrin** [comment]
I'm not sure problem is in out-of-bound access. Looks like broken wasm engine (according to emscripten comments)

http://nodeca.github.io/pica/demo/ - could try this demo with disabled wasm and enabled one, and tellme what happens?

**Comment by aurimasniekis** [comment]
We disabled wasm in our production application so it works. I understood from article that they added that error to not allow accessing out of bound values based on index masking

**Comment by puzrin** [comment]
There is no out of bound access in pica code. Seems wasm is broken in safary. That's a serious bug and i hope they will fix it, because many apps were affected. If they will not fix, i'll try to create a kludge for fallback.

**Comment by adamgins** [comment]
I am getting same issue on both Safari and Chrome on iOS 11.2.2

@puzrin with  the test I don’t see anything(no image) in the pica resize section

**Comment by grahams** [comment]
@adamgins FYI due to Apple restrictions, all web browsers/views/etc on iOS use Webkit, even Chrome.  So if one browser exhibits this behavior you should expect all would.

**Comment by lapponiandevil** [comment]
@aurimasniekis, did you somehow manage to disable wasm and still use pica, or did you only disable it for your own builds? I'm looking for a faste route to get up and running with resizing in iOS again.

**Comment by lapponiandevil** [comment]
Never mind, I didn't realize it could be such an easy thing to change as a parameter. So much for reading the docs huh!

**Comment by duyluandethuong** [comment]
@lapponiandevil Which parameter did you use? I try reading the docs but cannot find anything related to that.

**Comment by duyluandethuong** [comment]
Thanks @daohoangson, saw that and we are working on this.

**Comment by puzrin** [comment]
Since Webkit is still broken in IOS, i've released new pica version with better WebAssembly detection.

Let me know if issue solved or not.

**Comment by hu8373551** [comment]
This issue still exists on ios

**Comment by puzrin** [comment]
Are you sure you use latest pica? Can anyone else confirm?
