### ISSUE TITLE
Odd resize behaviour in Firefox & Safari

### ISSUE THREAD

**Issue by webprofusion-chrisc** [nodeca/pica#125]
Hi,
I recently ported an app to JS and used pica to do image resizes: https://apetools.webprofusion.com/

![image](https://user-images.githubusercontent.com/2445502/35784835-d1a89866-0a56-11e8-92d3-de029460738b.png)

The source for the app is at: https://github.com/webprofusion/apetools and the relevant part is https://github.com/webprofusion/apetools/blob/24a3736b12514777de590d13d9ee692ed15c6d6b/src/components/tools/tools.ts#L416

If I used my own basic resize (simpleImageResize) the scaling works, if I use pica resize it only really works in Chrome. I'm sure this was working before and my suspicion (which may be unfounded) is that it's something to do with recent browser patching regarding JS security flaws. Or I could just be doing something wrong.

Here's the firefox screenshot:
  
![image](https://user-images.githubusercontent.com/2445502/35785870-b7a1ffae-0a5e-11e8-9bc0-5cf2cfc3c853.png)

**Comment by puzrin** [comment]
1. Safary is already reported in other issue.
2. Does FF works in http://nodeca.github.io/pica/demo/ or not?

Also see comment about webworkify https://github.com/nodeca/pica#install

**Comment by lesuto** [comment]
We are experiencing this across all browsers...This has completely halted customer uploads -_-

**Comment by puzrin** [comment]
I can not help with debugging your code. Prior to report browser faults please make sure it's reproducible in existing demo.

**Comment by lesuto** [comment]
hello,

Thank you for the quick response.

All this was working as of last week.

There have been no code updates on our end and yet it is now broken.

I believe this is going to be an issue with Pica itself and how it maps the image to the canvas.

**Comment by puzrin** [comment]
This info is not enougth for report. Please do exactly what was requested:

1. try demo with defaults in browser http://nodeca.github.io/pica/demo/
2. If it fails, tell browser & OS version.
3. try demo with disabled webassembly checkbox.

**Comment by lesuto** [comment]
It was one of the default protocols that was causing this. Switching to JS only resolved the issue

**Comment by puzrin** [comment]
Since nobody confirmed FF on demo, close as duplicated (Safary already reported)
