### ISSUE TITLE
How do I resize multiple images

### ISSUE THREAD

**Issue by LarsWith** [nodeca/pica#126]
How do I resize multiple images with best performance?

In the docs I can see:

**(!) If you need to process multiple images, do it sequentially to optimize CPU & memory use. Pica already knows how to use multiple cores (if browser allows).**

Right now I have my images in a array that I loop and call this:

```
pica.resize(from, to)
  .then(result => pica.toBlob(result, 'image/jpeg', 0.90))
  .then(blob => console.log('resized to canvas & created blob!'));
```

for each image in inside the loop, but I am not sure if this is how you mean

**Comment by puzrin** [comment]
If you loop in async function, then that's ok.

**Comment by LarsWith** [comment]
@puzrin 
I am doing it like this

for (var i = 0; i < imgs.length; i++) {
pica.resize(imgs[i], to)
  .then(result => pica.toBlob(result, 'image/jpeg', 0.90))
  .then(blob => console.log('resized to canvas & created blob!'));
}

Is this okay?

**Comment by puzrin** [comment]
No.

```js
async function () {
  for (...) {
    await pica.resize(...)...
  }
}
```

Please avoid use this tracker for generic programming questions. There should be lot of tutorials how to chain promises.

**Comment by LarsWith** [comment]
@puzrin thx for the help and sorry for asking here. Anyway I solved it using recursion
