### ISSUE TITLE
Images (randomly?) corrupted with Firefox 58+

### ISSUE THREAD

**Issue by renchap** [nodeca/pica#130]
Hi,

I have been trying to debug this for some time and I would like to get your insight on this.

On my app, users can upload a lot of pictures, and I am using pica to resize them before uploading. On Firefox (saw this happening for users on mac, linux and windows) some images, not always the same when I try multiple times, are not correct once on the server. As I am calculating the checksum before upload, it is not caused by a network error.

Here is an example:
- Original image: https://www.dropbox.com/s/go5tra5czulbfsm/IMGL7717.jpg?dl=0
- Image after processing: https://www.dropbox.com/s/37n7ba5qhcl8vfq/314luvAL9s5OcI0ugieEKK-3cf7b61d9e.jpg?dl=0

I am using a code inspired by https://github.com/nodeca/nodeca.users/blob/master/client/users/uploader/uploader.js to extract the EXIF data, resize the image using `pica`, and then put it back together.
For each file:
- Read it using `readAsArrayBuffer`
- call `filterJPEG`
- create a new `Image`
- set the `src` using `window.URL.createObjectURL(file)`
- create 2 `canvas` elements, set their size
- draw the image on the first one
- call pica to resize on the second canvas (one shared pica instance, using `const pica = Pica({ idle: 10000 })`)
- get a blob from the `dst` canvas
- put back together the JPEG header (from `filterJPEG`) and the body from the blob

Once this is done, I use a webworker to calculate the MD5 checksum of the previously created `blob`, and upload it to my server (where the MD5 checksum is checked again).

Do you have an idea of what can cause this? There are a lot of moving parts and I am only seeing the issue on Firefox. I would estimate than less than 0.5% of the files are corrupted like this, and retrying a corrupted file usually works fine. I havent seen this problem on Safari / Chrome.

I know this may not be related to Pica, but I spent quite a lot of time trying to understand where it may come from, and I am not sure of how to pin it down.

Thanks!

__UPD__: probably a browser bug https://github.com/nodeca/pica/issues/130#issuecomment-371617724

**Comment by puzrin** [comment]
No ideas. Sorry, not enougth to keep this issue open. When you have proof (minimal reproducible code sample) that problem is in pica - post it here to reopen.

**Comment by Fensterbank** [comment]
Unfortunateley I can confirm this, but I'm not sure if it's a problem in this library.
I worked with FineUploader's resizing option and after I saw these random corrupted images I decided to use Pica to solve this and to get better quality.

But the problem remains.
I would have said it's a problem of FineUploader but since you are having this problem when reading the file directly an example would be good.

**Comment by renchap** [comment]
I took more time to test this, and it must be a bug with Firefox.
I have been able to reproduce it without Pica, just by resizing images with Canvas. I also reproduced it on Pica's demo after a lot of tries, on the 3 images displayed (original, pica resize and canvas resize).

it seems random to me. I saw a few bugs on Firefox tracker that might be related, and I am planning to automate a test to reproduce it, as I dont have a reproduction case that works more than 1% of the time.

**Comment by puzrin** [comment]
If this is FF bug, i could reopen issue when links to bugzilla available, to track progress.

**Comment by renchap** [comment]
This is definitely a FF bug with Canvas.
In another app I am using https://github.com/blueimp/JavaScript-Load-Image to resize images using Canvas and store thumbnails as data URLs, and I sometimes see corrupted images (like the one I posted above, bottom part of the image is white, sometimes its 80% of the image, sometimes more, sometimes less).
I will open a Firefox bug once I have a way to reproduce it, and will link it here. I plan to write a simple File => dataurl function and call it in a loop until it generated a corrupted image. I am trying to figure out how to detect that an image is corrupted, so I can automate the whole process.

**Comment by puzrin** [comment]
BTW, is this related to new FF versions only or not (i ask because nobody reported this problem before).

**Comment by renchap** [comment]
I got the first user reports in early February and I did not change anything related in my apps at this time, so it could be a bug introduced in Firefox 58 (released the 23rd of January).

**Comment by puzrin** [comment]
Ok, i'm open to any suggestions about kludges for FFm if that's possible. Already did browser workarounds (#89, #124). But i have no resources to inverstigate FF problem myself. If you need any help about pica internals - feel free to ask any questions.

**Comment by puzrin** [comment]
Updated title to make it look more like "browser bug" instead of "pica bug" (i hope so)

**Comment by puzrin** [comment]
Just an idea...

- try to wrap [`.toBlob()`](https://github.com/nodeca/pica/blob/17e179003dfd3a78fd990cebda175bb6ff36c00c/index.js#L512) into `setTimeout()`. Probably FF has races and final canvas is not updated by all tiles before save.
- try test with disabled webworkers.

 Not sure this helps, but costs nothing to check when test available.

**Comment by renchap** [comment]
Thanks. At the moment I think it is not directly related to the core Pica code, and I do not see how we could avoid using `canvas`.

I will try your `setTimeout` suggestion. I have been able to rule out webworkers as I can reproduce the issue just by using plain `canvas` without Pica.

I think I found a way to detect corrupted images. Here is an example of a corrupted image once converted to a data URL (with `canvas.toDataURL('image/jpeg', 0.9)` : https://gist.githubusercontent.com/renchap/4b94807e694440c9f7fc2e883a30c51a/raw/a3d04791304a3d1fd5a883fc069c1c3257b907a4/gistfile1.txt

It looks like checking if the last characters are just a repetion of the same pattern is a good enough test.
I am now working on a repro by taking one image chosen by the user and looping until I get a corruption (resizing it and generating a data URL for each pass).

This should make it easier to find out the exact factors, as currently my only way to repro it is to load 200 images on my website.

**Comment by puzrin** [comment]
I guess, minimal test should be something like this:

- Put image to canvas
- Copy by regions (tiles) to new canvas
- .getImageData() and compare result.

I still don't understand location of problem:

- reading tiles from source
- writing resized tiles to canvas
- .toBlob

Also pica use different techniques to extract tiles from src (sort by effectivity), you can hack source to try each. But with high probability problem is not in reading src but in writing result.

In theory, it's possible to combine binary RGBA buffers manually in pica, and draw result to canvas once. The same for extraction. But it's really shitty and consume more memory.

**Comment by puzrin** [comment]
Thanks for info. Do you have link to bugzilla?

**Comment by renchap** [comment]
Here is the bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1450302

**Comment by fuerte656** [comment]
Hello I have the same problem)
Firefox 59.0.2 (64-bit) at windows 10 and I think that is a firefox bug. If searching on google "firefox createobjecturl corrupted" this thread will be at first place of search results. Also, I am using pica for resizing images.

**Comment by renchap** [comment]
Closing this as Firefox 61 and Firefox ESR 60.1 have been released yesterday and they include the fix.
