### ISSUE TITLE
Support cancellation without throwing

### ISSUE THREAD

**Issue by afiedler** [nodeca/pica#137]
Thanks for Pica, it's really useful!

I'm using pica to resize images based on a user zooming in or out with the mouse wheel. I've debounced the `wheel` event, but sometimes the user might zoom in and out so fast that I need to cancel an in-progress resize. I have this working using the `cancelToken`, but even if I just resolve `cancelToken`, Pica still throws and causes a promise to be rejected. We need to catch all unhandled promise rejections on our site since those that are uncaught trigger an error in our logging software (and potentially someone will get paged if they are too high).

Is there a reason pica needs to throw here? It seems like just setting `canceled` to true will abort the in-progress resize:

https://github.com/nodeca/pica/blob/d6f6907fd85f7cd473381104f8831f52344ccbd2/index.js#L219-L225

Alternatively, I could somehow return the promise created by `opts.cancelToken.then()` can catch that, but that seems messy if we can just avoid throwing in the first place.

I'm happy to fix this and make a PR, but I was just curious if there was a reason for throwing before I change it.

**Comment by puzrin** [comment]
IMHO resolve means correct result with resized data. If this data can not be provided => reject. In other case you will have to test result for correctness. I think it's better to leave all as is.
