### ISSUE TITLE
`undefined` result on resize

### ISSUE THREAD

**Issue by gqgs** [nodeca/pica#139]
[https://jsfiddle.net/mgvqtydq/](https://jsfiddle.net/mgvqtydq/)

Version `4.1.0` is always resolving `undefined` for the `resize` function.

The fiddle behaves as expected (i.e., it returns the resized canvas element) if a version <= `4.0.2` is used. 

[https://jsfiddle.net/mgvqtydq/2/](https://jsfiddle.net/mgvqtydq/2/)

Tested on Linux: Firefox 59.0.2 (64-bit) and Chrome 65.0.3325 (64-bit).

**Comment by puzrin** [comment]
Do i understand right, that resulting canvas is filled properly, but not passed inside as promise param?

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/136a34a2c30937ff028a8cafe7793c382e5096f2/index.js#L531

Seems should be `return to;` instead.

/cc @rlidwka

**Comment by puzrin** [comment]
Should be fixed in 4.1.1. Let me know how is it.

**Comment by gqgs** [comment]
4.1.1 is behaving as expected. Thanks!
