### ISSUE TITLE
any example to use pica with typescript

### ISSUE THREAD

**Issue by mpoehler** [nodeca/pica#141]
Hi, I want to use pica in typescript and doesn't find a way to use it.

Is there a type file somewhere?

**Comment by puzrin** [comment]
This question is out of this project scope.

**Comment by denxorz** [comment]
If anybody lands here, install:
`npm i @types/pica --save-dev`

Then import:
`import Pica from 'pica';`

Then use:
```
const pica = Pica();
pica.resize(from, to);
```
