### ISSUE TITLE
Resize promise resolved but canvas seems like not ready

### ISSUE THREAD

**Issue by Diwei-Chen** [nodeca/pica#142]
Hi,

We have the following code to resize an image object,
```
var targetCanvas = document.createElement("canvas");
await pica.resize(img, targetCanvas)
		.then(result => {
                    var newJPG = result.toDataURL('image/jpeg');
                    var img = new Image();
                    img.onload = function() {
                        var inserted = piexif.insert(exifbytes, newJPG);
                        resolve(inserted);
                    };
                    img.src = newJPG;
	        })
                .catch((error) => {
                console.log("pica resize error", error);
                });
```
after the resize promise is resolved, we upload the image to our server. 

However, it happens randomly that the new image object is broken and nothing is uploaded.

But if we put a setTimeout 2000 ms around the result, like:
```
await pica.resize(img, targetCanvas)
	        .then(result => {
                    setTimeout(function(){
                    var newJPG = result.toDataURL('image/jpeg');
    				var img = new Image();
    				img.onload = function() {
    					var inserted = piexif.insert(exifbytes, newJPG);
    					resolve(inserted);
    				};
    				img.src = newJPG;
                    }, 2000);
		})
                .catch((error) => {
                    console.log("pica resize error", error);
                });
```
then it works fine.

Any ideas why it behaves like this, please?

Our pica settings is:
```
if (gIsiOS()) {
    pica = require('pica/dist/pica')({ features: [ 'js' ] });
} else {
    pica = require('pica/dist/pica')({ features: [ 'js', 'wasm' ] });
}
```
and the image is broken on both iOS 11.3 and Desktop browser: Chrome and Safari.

**Comment by puzrin** [comment]
AFAIK wasm detector now works in iOS right, and tweaking features is not needed anymore.

Why canvas is not ready - no ideas. Writing data to canvas is sync, and i can't change there anything. I'd suggest first to drop `.toDataURL()` use, it's ancient. See [our code](https://github.com/nodeca/nodeca.users/blob/1a86edfd910cd8af11bd3a0fd2ed8c264fe72683/client/users/uploader/uploader.js#L134), we use `pica.toBlob()`, it's more effective and modern. Let me know if that helps. I have no big user base to catch such errors (and i'm not "web developper", my strong side in this project is writing fast math in js)

**Comment by Diwei-Chen** [comment]
Thanks @puzrin 
We just tried with `pica.toBlob()` suggestion as:
```
await pica.resize(img, targetCanvas)
            .then(() => pica.toBlob(targetCanvas, 'image/jpeg'))
            .then(function(blob) {
                const fr = new FileReader();
                fr.onload = function(e) {
                    const newJPG = e && e.target && e.target.result;
                    var img = new Image();
                    img.onload = function() {
                        var inserted = piexif.insert(exifbytes, newJPG);
                        resolve(inserted);
                    };
                    img.src = newJPG;
                };
                fr.readAsDataURL(blob);
            })
            .catch((error) => {
                console.log("pica resize error", error);
            });
```
And added wasm back for iOS, but still no luck.
It normally happens when our users upload the first resized image, but all subsequent resized images uploads work fine.

**Comment by puzrin** [comment]
Probably some new nasty iOS bug. It would be nice to collect a bit more info, may be someone else who read this repo can help

- If error thrown, what is in it?
- What is content of the blob when error happens? Can this be a problem of FileReader as in recent FF https://github.com/nodeca/pica/issues/130#issuecomment-377548742?

**Comment by Diwei-Chen** [comment]
Sorry, for our use case, this happens to us on Desktop browsers - Chrome and Safari as well.

Re. the questions:

- No error thrown. Promises are resolved. 
- Size and mimetype etc. of the blob content are right. Size reflects correctly after resizing. But it seems like the actual data is just not there. We looked through https://github.com/nodeca/pica/issues/130 and checked there is no repeated chars at the end of (the broken image dataUrl)[https://drive.google.com/file/d/1_wo0ScUpGzVs7OgCHnghiOHou9aAGafQ/view?usp=sharing]. Sorry, this may be not related to FF cos it breaks even we are on other browsers.

We just did some quick experiments with the setTimeout method mentioned above and here are the results:

1. setTimeout with 500ms, 1000ms, 2000ms, respectively - can't see any images broken with around 20 tries each case.

2. setTimeout with 100ms, 0ms - the chance of seeing broken images is relatively high - one out of four tries.

From what is shown to us, we could believe that after the resize promise is resolved, there might be chances that the canvas is ready to be transformed.

**Comment by puzrin** [comment]
1. JPEG size depends on content. It can not be right if content is different. Try to compare partial blocks or md5 checksums of good/bad result. I think it will be more simple to use toDataURL() for testing, because access to it's content is sync and because filereader may glitch.
2. Canvas operations (tiles write) are sync, it can not be "not ready" after function call, according to docs.

**Comment by Diwei-Chen** [comment]
Thanks for the quick reply.

I may be off tomorrow and will come back to you with the md5 checksums test results early next week.

**Comment by Diwei-Chen** [comment]
Just checked and got the same [md5](https://www.npmjs.com/package/md5) hash code: `a92cb5348dccce1d43aa833de6ab55d8` for both good and bad results.

**Comment by puzrin** [comment]
Close as not related to pica then?

**Comment by Diwei-Chen** [comment]
Yep, maybe the issue is caused by some other bug in our code.

Thanks a lot.
