### ISSUE TITLE
UI become unresponsive

### ISSUE THREAD

**Issue by saumyamehta17** [nodeca/pica#143]
Hi,

I am using pica to resize images as user uploads which make UI unresponsive, which actually don't using web workers later I realised when I saw in features being used by pica. Can you please guide me why it is not using web workers or what is required to make it use web workers?

const pica = require('pica')({ features: [ 'js', 'wasm', 'ww'] })
pica.resize(img, resizedCanvas, {
        unsharpAmount: 80,
        unsharpRadius: 0.6,
        unsharpThreshold: 2,
        transferable: true
    }).then(() => {
        let resizeTime = (performance.now() - start).toFixed(2);
        pica.toBlob(resizedCanvas, 'image/jpeg', 0.90).then((blob) => {
            let url = URL.createObjectURL(blob);
           store.dispatch(setToThumbnailCache({key: image_uuid, val: url, type: 'thumbnail'}));
    })
});

**Comment by puzrin** [comment]
Probably you try to build pica from sources via webpack. See note https://github.com/nodeca/pica#install
