### ISSUE TITLE
TypeScript typings.

### ISSUE THREAD

**Issue by TheCelavi** [nodeca/pica#145]
Ok, this is just a snapshot preview, I didn't exposed method "resizeBuffer", I didn't use it, so I do not know what does it returns with Promise.

@puzrin When you see this code, you will be clear what I have done - could you verify if this is ok, at least at first glance?

And in regards "resizeBuffer" method, what is returned with promise ("Result is Promise, resolved with resized rgba buffer" - what is that, which type? String?);

Thanks!

```typescript
declare module 'pica' {
    export = Pica;
}

declare module 'pica/dist/pica' {
    export = Pica;
}

declare class Pica {

    constructor(configuration?: Configuration);

    public resize(source: HTMLElement, destination: HTMLElement, options: Options): Promise<HTMLCanvasElement>;

    public toBlob(canvas: HTMLCanvasElement, mimeType: string, quality?: number): Promise<Blob>;
}

interface Configuration {
    tile?: number;
    features?: Array<string>;
    idle?: number;
    concurrency?: number;
}

interface Options {
    quality?: number;
    alpha?: boolean;
    unsharpAmount?: number;
    unsharpRadius?: number;
    unsharpThreshold?: number;
    cancelToken?: Promise<any>;
}

```

**Comment by puzrin** [comment]
1. IMHO it could be helpful to restrict `config.features` to "enum", if it's possible. Will help against mistypes.
2. As far as i remember, `.resizeBuffer` should return `Uint8Array`.

Note, i could accept PR, but there can be problems with maintenance. May be it will be better to publish it via https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by TheCelavi** [comment]
Agree.

Options for resize - seams that two options are missing, toWidth and toHeight? Am I right? Seams that it missing in README as well, it can be used successfully... Or resized width and height should be specified differently?

**Comment by puzrin** [comment]
`.toWidth` and `.toHeight` are taken internally from destination canvas (or, probably, that can be mess from previous version). I have no ideas why anyone may wish to define those directly. IMHO it does not worth to expose those into definitions.

**Comment by TheCelavi** [comment]
Hey, I thing I got it why I use it - for custom resize when I do not render resized image on page (per example, resize and upload to server smaller image).

If target canvas is created programmatically but not added to DOM, then there is an issue in resize, it can not determine properly dimensions of the canvas.

**Comment by puzrin** [comment]
https://github.com/nodeca/nodeca.users/blob/e6c1599b07c9a438846349ad293d4bd0255177e1/client/users/uploader/uploader.js#L122-L133

That works as expected, you do something wrong.

**Comment by puzrin** [comment]
I think it's time to close this

**Comment by denxorz** [comment]
If anybody lands here, install:
`npm i @types/pica --save-dev`

Then import:
`import Pica from 'pica';`

Then use:
```
const pica = Pica();
pica.resize(from, to);
```
