### ISSUE TITLE
CSP error - Refused to compile or instantiate WebAssembly module because 'wasm-eval' is not an allowed source of script in the following Content Security Policy directive

### ISSUE THREAD

**Issue by pablogravielseo** [nodeca/pica#146]
Hi, I got the following error: `Refused to compile or instantiate WebAssembly module because 'wasm-eval' is not an allowed source of script in the following Content Security Policy directive`:

![csp-error](https://user-images.githubusercontent.com/1693105/42956693-0a321fa0-8b57-11e8-8e3b-30c282740826.png)

I have tried to add "wasm-eval" in CSP but nothing, same error appears, I have searched about too but nothing.

**Comment by puzrin** [comment]
https://github.com/WebAssembly/content-security-policy/issues/7

Seems you need unsafe-eval. Type error message in google and see results.

https://github.com/nodeca/pica/blob/e12af7c3a4d47db0537688e924dc304d6296f75e/dist/pica.js#L1467

Appropriate code is wrapped into try/catch, don't know why this is not handled. If you have idea how to improve detection logic - let me know.

**Comment by pablogravielseo** [comment]
Hi @puzrin, the value "unsafe-eval" is already present in script source and the same error continue. 
Seems that fallback to JS implementation.

![picajs-csp-wasm-eval-error](https://user-images.githubusercontent.com/1693105/43144670-129f7242-8f34-11e8-9e36-cbd552bb20ba.png)

I'm still looking for a solution.
