### ISSUE TITLE
IE 11 Bug

### ISSUE THREAD

**Issue by sezgin02** [nodeca/pica#148]
https://github.com/nodeca/pica/blob/44a37e9ec7602ee46e7d7388b374febd872e5281/index.js#L36

There is a bug for IE 11, which is not able to handle shorthand property names. The fix should be easy.

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/44a37e9ec7602ee46e7d7388b374febd872e5281/package.json#L23-L34

You should use proper browserifier setup, or file from `dist/` folder.
