### ISSUE TITLE
Webpack React - docs

### ISSUE THREAD

**Issue by BernardA** [nodeca/pica#149]
I checked the other issues related to Pica/Webpack, but that did not solve my problem.

Could you please, make an explicit recipe for using npm/Webpack?

I have a React project, built with npm/Webpack as most are. So using browserify is not an option, I believe. 

So, reading your docs I have made a few attempts:
1 -
> npm install --save pica // or just npm install pica

Then on the concerned script:

> const pica = require('pica/dist/pica');

That will throw an error when attempting to process the image:

> TypeError: pica.resize is not a function

2 -

If instead I use 

> import * as pica from 'pica/dist/pica.js';

I get a similar error:

> TypeError: __WEBPACK_IMPORTED_MODULE_11_pica_dist_pica_js__.resize is not a function

In fact, already the Visual Studio Code will show a warning as:

> Could not find a declaration file for module 'pica/dist/pica.js

Thanks

**Comment by puzrin** [comment]
Files in `dist/` folder uses standard UMD wrapper. That should be handled well by everything. But i don't use webpack and can't comment details about it. IMHO this question is a bit out of project scope.

**Comment by BernardA** [comment]
Thanks @puzrin, but Webpack is by far the most used bundler and it would be a pity if your tool could not work well with it.

**Comment by puzrin** [comment]
Other people use pica with webpack. But as i said, you probably selected a wrong place to ask your question.

**Comment by BernardA** [comment]
It does not seem that "other people" are being any more successful than I am:
https://github.com/nodeca/pica/pull/72
https://github.com/nodeca/pica/issues/70

**Comment by VarLog** [comment]
Hello!

I investigated the problem with pica and wepback and I hope that I found a solution.
It's simple, just define alias for pica in your webpack config:

```

**Comment by puzrin** [comment]
@BernardA i'd suggest to be constructive. As soon as CORRECT solution will be possible, it will be used.

**Comment by puzrin** [comment]
@VarLog looks interesting. Can this affect other build systems? The only reason why none previously suggested fix was appied yet - because improving in one place breaks something different.

**Comment by puzrin** [comment]
@VarLog AFAIK readme already contains note to use direct path to prebuild file. Are you sure more alternatives will add value?

**Comment by VarLog** [comment]
@puzrin I think so, because when I tried just use `import pica from 'pica/dist/pica';` it didn't work. Then I tried to use `require(pica/dist/pica)` and it wasn't successfully too. After that I wasted a couple of hour to find solution how can I make pica to work with webpack. :)
I can create a PR for it.

**Comment by VarLog** [comment]
@puzrin Please, take a look at https://github.com/nodeca/pica/pull/154
