### ISSUE TITLE
LinkError: WebAssembly Instantiation: Import #0 module="env" function="memory" error: memory import must be a WebAssembly.

### ISSUE THREAD

**Issue by vedtam** [nodeca/pica#150]
Hi,

I'm trying to use the `resizeBuffer` method, but it throws:

`Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #0 module="env" function="memory" error: memory import must be a WebAssembly.Memory object
    at MathLib.instance [as __instance] (http://localhost:8081/node_modules/pica/dist/pica.js:1168:32)
    at MathLib.resize_wasm [as resize] (http://localhost:8081/node_modules/pica/dist/pica.js:551:29)
    at MathLib.resizeAndUnsharp (http://localhost:8081/node_modules/pica/dist/pica.js:90:27)
    at http://localhost:8081/node_modules/pica/dist/pica.js:2206:35` 

code:

```
...

const pica = window.pica();

for (var i=0; i < files.length; i++){
  ((_file) => {

    var img = new Image();

    img.onload = function () {    
      var reader = new FileReader();
      reader.onload = function(){
      
        pica.resizeBuffer({
          src:reader.result,
          width:this.width,
          height:this.height,
          toWidth:1000,
          toHeight:1000,
          quality: 3,
          unsharpAmount: 80,
          unsharpRadius: 0.6,
          unsharpThreshold: 2,
          alpha: true,
        }).then(result => { console.log(result) });

      }

      reader.readAsArrayBuffer(_file);
    }
    img.src = window.URL.createObjectURL(_file);

  })(files[i]);
}

...
```

Are eventually any more dependencies I need to import along with pica.js?

I would really appreciate your help.
Thanks!

**Comment by puzrin** [comment]
In what env do yo try to run this code?

**Comment by puzrin** [comment]
Does existing demo works there?

**Comment by vedtam** [comment]
The method `pica.resize(from, to)` and `.toBlob` work but I keep struggling with the `.resizeBuffer()` method.

I have tried to move `.resizeBuffer()` into a worker:

main.js:

```
...
<body>

    <input type="file" name="" onchange="runPica(this)" value="">
    <img src="" alt="">

    <script>
      var worker = new Worker("worker.js");

      worker.onmessage = function(event) {
        var blob = new Blob([event.data], {type:'image/jpeg'});
        console.log('back in main.js, this is our blob:');
        console.log(blob);
        document.querySelector('img').src = window.URL.createObjectURL(blob);
      };

      function runPica(input){

        let img = new Image();
        img.onload = function(){

          var reader = new FileReader();
          reader.onload = function(){
            worker.postMessage({buff: reader.result, width:img.width, height:img.height});
          }

          reader.readAsArrayBuffer(input.files[0]);
        }
        img.src = window.URL.createObjectURL(input.files[0]);
      }

    </script>
  </body>
```

worker.js:

```
onmessage = function(e) {

  console.log('arrayBuffer going into pica:');
  console.log(e.data.buff);

  console.log(`width going into pica: ${e.data.width}, height: ${e.data.height}`);

  pica().resizeBuffer({
    src:e.data.buff,
    width:e.data.width,
    height:e.data.height,
    toWidth:600,
    toHeight:800,
    quality: 3,
    unsharpAmount: 80,
    unsharpRadius: 0.5,
    unsharpThreshold: 2,
    alpha: true,
  }).then(result => {
    postMessage(result);

    console.log('Pica result:');
    console.log(result)
  });

}
```

now console throws:

![screen shot 2018-08-24 at 22 27 57](https://user-images.githubusercontent.com/4981592/44604161-b163de00-a7ed-11e8-8dcb-e76f2bd995c8.png)

if I change the widht height of the `resizeBuffer()` method inside the worker to say widht: 2000, height: 2000,
the code runs but the returning Uint8Array is all 0 0 0 0 0:

![screen shot 2018-08-24 at 22 23 32](https://user-images.githubusercontent.com/4981592/44604244-ef610200-a7ed-11e8-83e0-72cfb26fc216.png)

**Comment by puzrin** [comment]
I guess, you question is not about library bug. So, prefer to not keep this issue open.

I can't help with your code debugging, but could advice this things:

- First, remove your source builder and use precompiled files from `/dist`. See readme note, that webpack does not support inlining webworkers.
- Take this test as start point https://github.com/nodeca/pica/blob/e12af7c3a4d47db0537688e924dc304d6296f75e/test/fixture_resize.js#L106-L148 it's ok with `.resizeBuffer()`.
- Make sure, that input is typed array and width/height are correct. That's a common mistake. Input MUST be typed array and contain raw RGBA data.
- Don't use `.resizeBuffer()` without need. That's a low-level interface, for geeks only :)

**Comment by vedtam** [comment]
Hi,

The issue was with the data I was trying to feed the method, it wasn't Uint8Array and had no raw RGB. I found inkjet which does a nice job with the above mentioned.

Thanks!

**Comment by puzrin** [comment]
Also note, `.resizeBuffer()` just apply pure scaling filter math, without clever things like tiling (to save memory), webworkers (for parallel processing) and so on. I know only one case, when you really may need this - if you write jpeg decoders :).

In general, it will be much better to use `.resize()`, you will avoid a lot of troubles.

**Comment by vedtam** [comment]
Hi,

Thanks for your suggestions I really appreciate, yes,`.resize()` would be enough but the web app I'm working on, is about importing, editing and uploading a large number of images (200+) each of a size ~8 MB (depending on the phone's camera). 

The first step, the app does is resizing the list of selected images (can go up to 100 photos at once) and canvas couldn't handle it (killed the main thread), so I started experimenting and doing some benchmarks using `.resize()` and the above mentioned `.resizeBuffer()`. I would love to avoid canvas entirely for the resize operation.

While experimenting I started to like working with typed arrays, raw binary data and bitwise operators, its really interesting, reason I wanted to try different approaches and learn along the way.

**Comment by vedtam** [comment]
Hi,

I wen't on and use `.resize(img, canvas)`. However I have a question regarding the orientation of the image. I used the below method to translate `ctx` for the right orientation in case, but now this won't work because `putImageData()` inside pica ignores my context rotation. 

Do you have any suggestion on where I should apply rotation of the context to get my orientation right?

```
    img.onload = function () {
         var ratio = Math.min(1000 / this.width, 1000 / this.height);
          var width = Math.floor(this.width * ratio);
          var height = Math.floor(this.height * ratio);

          that.getOrientation(_file, function(srcOrientation){
            if (4 < srcOrientation && srcOrientation < 9) {
              canvas.width = height;
              canvas.height = width;
            } else {
              canvas.width = width;
              canvas.height = height;
            }

            switch (srcOrientation) {
              case 2: ctx.transform(-1, 0, 0, 1, width, 0); break;
              case 3: ctx.transform(-1, 0, 0, -1, width, height); break;
              case 4: ctx.transform(1, 0, 0, -1, 0, height); break;
              case 5: ctx.transform(0, 1, 1, 0, 0, 0); break;
              case 6: ctx.transform(0, 1, -1, 0, height, 0); break;
              case 7: ctx.transform(0, -1, -1, 0, height, width); break;
              case 8: ctx.transform(0, -1, 1, 0, 0, width); break;
              default: break;
            }

         pica.resize(img, canvas)
              .then(result => document.body.appendChild(result))

         ...
```

Thanks!

**Comment by puzrin** [comment]
Orientation is "logical" param, not physical. That does not fit into this library scope, and should be processed separate. I'd suggest to dig this source https://github.com/nodeca/nodeca.users/blob/master/client/users/uploader/uploader.js, there are many things to do except resize, to process image file properly. For example, you may wish to drop big previews from EXIF, etc.

I can not guarantee that linked source is correct, not battle tested yet on big volumes.

**Comment by puzrin** [comment]
As far as i remember, `Image` tag applies orientation and you can skip processing if you are not going to to reuse old EXIF with scaled image.

**Comment by porfirialex** [comment]
HI @vedtam Could you solve the issue with orientation?  you have any example?
