### ISSUE TITLE
suggestion for demo page CSS... body { image-rendering: crisp-edges; } // to exhibit your canvases unmunged when user-zoomed

### ISSUE THREAD

**Issue by Techsita** [nodeca/pica#151]
I admire your work here (I stumbled across it, with no present need for it) and I enjoyed playing with your demo!

I noticed a commonplace UX image quality gotcha on your demo page for "mobile" browsers (tablet or phone) where users may commonly pinch zoom, which is a sensible thing for the user (e.g. me!) to do, as we expand to better "see the pixels" to closely compare your three demo canvases.

Modern browsers default to "auto" mode for images (and canvas) when zooming is to actively smooth the render of rescaled elements, so, for your demo, this defeats the whole purpose of the user expanding to better see how your cases compare (and also ruins any screenshot-ing of same).

CSS is a single line rule fix: body { image-rendering: crisp-edges; }
(no difference imposed when 1:1 scaling render) for references see... 
https://caniuse.com/#feat=css-crisp-edges

I suspect this also "fixes" exact intended isomorphism for renders that are being somewhat lied to about size due to devicePixelRatio not being 1 (e.g. "retina" high dpi displays), although most code for modern canvas use should already have coped with that issue somehow.

Thanks again, loved the clarity of your demo page!

P.S. I keep a bookmarklet handy to force this render behavior, e.g. roughly...
javascript:document.body.style.imageRendering = [ "auto" , "crisp-edges" , "pixelated" ][1]; void(0);

**Comment by puzrin** [comment]
That's just a demo, to show difference somehow. I think it do this job and has no need to change. But you can send PR with improvements if you wish.
