### ISSUE TITLE
Unminified Dist Includes Minified Source

### ISSUE THREAD

**Issue by jlukic** [nodeca/pica#152]
It looks like Pica includes minified code in line 01 of [the unminified dist file](https://github.com/nodeca/pica/blob/master/dist/pica.js)

We were hoping to use the unminified dist in our build pipeline but were receiving errors on this line that I would surmise might be caused by reminifying already minified code.

**Comment by puzrin** [comment]
That's a standard line added by `browserify`. Everything works as needed.
