### ISSUE TITLE
CIB fails doing unsharp

### ISSUE THREAD

**Issue by lahdekorpi** [nodeca/pica#160]
Running Chrome 72.0 (canary) where CIB is enabled by default results in this error:
```
TypeError: _this2.__mathlib.unsharp is not a function
    at pica.js:1923
```

**Comment by puzrin** [comment]
Need more details, why you decided bug is related to this package. Is it reproducible in http://nodeca.github.io/pica/demo/ ?

**Comment by lahdekorpi** [comment]
Oh, sorry for the vague bug report. Now that I look at it, this clearly needs more context.

Yes, the issue happens with said demo and with a stock Chrome (canary) install when you enable CIB in the demo.

It seems to fail here https://github.com/nodeca/pica/blob/master/dist/pica.js#L1928

There was no source map file for the demo JS, so I'll have to look a bit more in detail.

**Comment by lahdekorpi** [comment]
After disabling unsharping, CIB works perfectly.

**Comment by lahdekorpi** [comment]
Should unsharping even work in the demo using CIB?

If I understood the code correctly (I'm new here), unsharping is done with multimath and it provides a JS and WASM version of this? But `createImageBitmap` directly returns a Promise resolving to an ImageBitmap. And only has a `resizeQuality` option.  
Would the unsharping have to be done to this ImageBitmap?

**Comment by giox069** [comment]
Similar problem appeared recently on my Android Phone, with Chrome updated to version 70:
```Uncaught (in promise) TypeError: c.__mathlib.unsharp is not a function```
when calling resize with unsharpAmount: 80.
Setting unsharpAmount to 0 fixes it.

**Comment by agusterodin** [comment]
Image uploads on my site fail now due to Uncaught (in promise) TypeError: c.__mathlib.unsharp is not a function error. As previously mentioned, turning unsharpAmount to 0 fixes it but isn't that detrimental to image quality. Isn't s main point of the library to apply unsharp mask?

**Comment by rlidwka** [comment]
Fixed, thanks for reporting. Forgot to rename a function after multimath rewrite.
