### ISSUE TITLE
Pica vs Gimp

### ISSUE THREAD

**Issue by linluc** [nodeca/pica#162]
When scaling the same image file, GIMP can produce output 10 times smaller than Pica. This is with Gimp's default setting (quality=90).

Is this a general scaling in a browser (or using JS) limitation? I only tested Pica using the demo page, can I achieve much better size reduction results once I embed Pica in my code and play more with params? I am primarily interested in size reduction for image uploading purposes and somehow no browser based method I've tried can get even remotely close (in terms of image size reduction) to Gimp. Image quality is not that important to me and Gimp's quality param 90/100 definitely meets my needs.

Thanks for the library and your support!

**Comment by puzrin** [comment]
https://github.com/nodeca/pica#toblobcanvas-mimetype--quality---promise

Use `quality` param to reduce blob size. Result will depend on browser details, and may differ from gimp.
