### ISSUE TITLE
Resize fails on Android Firefox when running with WebAssembly

### ISSUE THREAD

**Issue by sbugert** [nodeca/pica#164]
I'm getting this error on the demo website using Firefox (63.0.2) on Android (Galaxy S8, Android 7.0):
`RuntimeError: index out of bounds`

It seems to work if WebAssembly is disabled.

The error in my own code provides some more context with a stack trace:

```
Unhandled promise rejection RuntimeError: "index out of bounds"
	<anonymous> http://localhost:8000/commons.js line 14956 > eval line 70 > WebAssembly.compile:wasm-function[3]:0x382
	unsharp home/bugert/repos/jabcode/node_modules/multimath/lib/unsharp_mask/unsharp_mask_wasm.js:45:3
	resizeAndUnsharp home/bugert/repos/jabcode/node_modules/pica/lib/mathlib.js:43:5
	invokeResize home/bugert/repos/jabcode/node_modules/pica/index.js:312:39
	run home/bugert/repos/jabcode/node_modules/core-js/modules/es6.promise.js:75:22
	notify home/bugert/repos/jabcode/node_modules/core-js/modules/es6.promise.js:92:30
	flush home/bugert/repos/jabcode/node_modules/core-js/modules/_microtask.js:18:9

```

EDIT: Also, as expected, it succeeds when unsharp is set to 0 (turned off).

**Comment by puzrin** [comment]
Is this reproducible with 5.0.1?

**Comment by puzrin** [comment]
Can not reproduce in FF68, probably related to #160.

If no update available - issue will be closed as outdated.

**Comment by puzrin** [comment]
Close - no updates, probably no longer exists.
