### ISSUE TITLE
Fails to build in webpack 4

### ISSUE THREAD

**Issue by pradsdev** [nodeca/pica#165]
#### Error

![screen shot 2018-11-28 at 4 07 34 pm](https://user-images.githubusercontent.com/22481058/49146669-a490e200-f328-11e8-82f3-a19c31c9d48a.png)

### Steps to reproduce

1. Create vue project using `@vue/cli`- `3.2.1` with default configuration
2. Install `pica`- `5.0.0` through `npm`

### Expected
Zero Errors

**Comment by puzrin** [comment]
https://github.com/nodeca/pica#install

use file from dist folder or tune webpack config
