### ISSUE TITLE
worker are not working caused by forcing ` require('webworkify') `

### ISSUE THREAD

**Issue by maple-leaf** [nodeca/pica#169]
In chrome, init pica with `pica({ features: [ 'js', 'wasm', 'ww'] });`, but worker will not being used caused by error raised in below code:

```javascript
 // IE <= 11 don't allow to create webworkers from string. We should check it.
      // https://connect.microsoft.com/IE/feedback/details/801810/web-workers-from-blob-urls-in-ie-10-and-11
      try {
        let wkr = require('webworkify')(function () {}); // <-- this will raise error
        wkr.terminate();
        this.features.ww   = true;
```
maybe we should detect browser firstly and decide if `webworkify` is required? Or give more infos and advices about this on readme?

**Comment by puzrin** [comment]
See webpack notice and use appropriate build https://github.com/nodeca/pica#install
