### ISSUE TITLE
Can we have some instructions please for web apps without a build step?

### ISSUE THREAD

**Issue by bbsimonbb** [nodeca/pica#170]
I can't be alone... I've got a web app that's a glorious mix of XSL and some Vue. We have no build step for the moment, so no node, no browserify. It should still be possible to use Pica, no?

**Comment by puzrin** [comment]
pica is available in compiled form as umd module in https://github.com/nodeca/pica/tree/master/dist

**Comment by bbsimonbb** [comment]
That's marvellous thanks very much.
