### ISSUE TITLE
Problem on iphone

### ISSUE THREAD

**Issue by lucasthibau** [nodeca/pica#172]
iPhone does not work.

Debugging the lib, i've seen that in Android it enters in 
`if (_this2.features.cib)` (~ line 1936)
where cib gets a true value on android.
In iphone it gets a false value.
running into other line and breaking in 
`var _stages$shift = stages.shift(),
                            _stages$shift2 = _slicedToArray(_stages$shift, 2),
                            toWidth = _stages$shift2[0],
                            toHeight = _stages$shift2[1];`
because some values are null.

**Comment by puzrin** [comment]
http://nodeca.github.io/pica/demo/

Does demo works?

**Comment by lucasthibau** [comment]
Yes, it does.

I've tried the both:
In the pica.resize that's commented, it generates the error:
"_this2.__mathlib.unsharp is not a function"

            dst = {};
            const resizedCanvas = document.createElement("canvas");
            var imgmedidas = new Image();
            imgmedidas.onload = function () {
                dst.width = 1000;
                dst.height = (this.height * 1000) / this.width;

                resizedCanvas.height = dst.height;
                resizedCanvas.width = dst.width;

                var pica;
                var resizer_mode = {
                    js: true,
                    wasm: true,
                    cib: true,
                    ww: true
                };
                var opts = [];
                Object.keys(resizer_mode).forEach(function (k) {
                    if (resizer_mode[k]) opts.push(k);
                });

                pica = window.pica({ features: opts });

                pica.resize(input.files[0], resizedCanvas)
                    .then(result => {
                        return pica.toBlob(result, 'image/jpeg', 0.90);
                    })
                    .then(function (blobImg) {
                        window.alert(blobImg);

                //pica.resize(input.files[0], resizedCanvas, {
                //    quality: 3,
                //    alpha: true,
                //    unsharpAmount: 80,
                //    unsharpRadius: 0.6,
                //    unsharpThreshold: 2,
                //    transferable: true
                //})
                //    .then(function (blobImg) {
                //        window.alert(blobImg);
            }

**Comment by puzrin** [comment]
If demo works, what king of bug do you report here? I can't debug your code.

**Comment by lucasthibau** [comment]
Didn't found any referrences or similar bugs.

**Comment by puzrin** [comment]
Bug in your code != bug in this package. Please provide a clear and small reproducible simple, to prove bug is in this package. Then i will reopen issue.

**Comment by lucasthibau** [comment]
Thanks for helping the community! =D
