### ISSUE TITLE
Support for use with react-scripts

### ISSUE THREAD

**Issue by ximenean** [nodeca/pica#175]
I'd like to use this library in a project that uses react-scripts (@2.1.5) but it doesn't seem possible to use webworkers in this scenario.

From what I can tell, if I add a `main: dist/pica.js` to the `package.json` of this project it seems to work correctly and runs the webworker.

Alternatively, in my code I can always do `import Pica from "pica/dist/pica"` but changing the `package.json` might make it easier to use perhaps.

I'm not so familiar with Browserify, but could this be added without a knock-on effect? I'm happy to submit a PR

**Comment by puzrin** [comment]
See previous issues. I don't like to change development process (require rebuild after every change). That was discussed somewhere. Problem is not in PR, problem is how to do it convenient for all, without ugly side effects.

But i'm open to suggestions.
