### ISSUE TITLE
How to handle uploaded files?

### ISSUE THREAD

**Issue by BananaAcid** [nodeca/pica#178]
(PWA) Is there a way to handle files from an file-input / pouch-db-attachment (blob) to not be drawn to a canvas first to be able to use resizing? And only wanting the blob, is there a way around an output canvas?

**Comment by puzrin** [comment]
You may try to search image decompressor lib and use it manually, then call `.resizeBuffer()`. Such questions are out of project scope

**Comment by BananaAcid** [comment]
It might be an idea, to add this to the documentation.
