### ISSUE TITLE
Nearest neighbor too good?

### ISSUE THREAD

**Issue by manuelcabral** [nodeca/pica#18]
I was testing pica with quality == 0 against an implementation I made of nearest neighbor interpolation and noticed that the image from pica was much smoother. Analysing pica's code I noticed that `filterSize` is 8 with quality 0. Shouldn't the `filtersize` be 1 in this case? Did I misunderstand how this interpolation works?

**Comment by puzrin** [comment]
Box fiter use window 0.5, that can be more than 1 pixel https://github.com/nodeca/pica/blob/master/lib/pure/resize.js#L19 . That's not exactly "nearest neighbour".

On practice, quality 0-2 were done just for fun, to understand filters difference. Only quality 3 (lanczos3) make sense for real use. I'd recommend to use skia src as source of info. Pica is a simplified ans js-specific implementation of the same things.
