### ISSUE TITLE
PNG Transparency is not ruined

### ISSUE THREAD

**Issue by itai-adonis** [nodeca/pica#182]
Hey, 
Tried to resize / compress using Angular 8 .
Its working AMAZING , however, resizing a PNG transparent file is not keeping the transparency.
Appreciate if you could handle that as well.
Thanks for your great work!

**Comment by samuelmaddock** [comment]
Did you set the `alpha` option to `true`?
https://github.com/nodeca/pica#resizefrom-to-options---promise

**Comment by puzrin** [comment]
Close. See `alpha` option and #60.
