### ISSUE TITLE
Canvas bug in Chrome using hardware acceleration

### ISSUE THREAD

**Issue by elisbyberi** [nodeca/pica#187]
#### Solution
1. Turn off Chrome hardware acceleration.
2. Or,  decode and encode images using JavaScript and/or WebAssembly.

#### Test case
Chrome 80.0.3987.87 **using hardware acceleration**.
Ubuntu 14.04 Operating System
AMD Athlon(tm) II X2 220 Processor
GeForce 6150SE nForce 430 Graphic Processor

#### Result
1. It can not create a correct canvas using JavaScript and WebAssembly.
2. Using createImageBitmap does work sometimes drawing a blank canvas randomly.

#### Question
It is not possible to disable hardware acceleration using JavaScript.
Is it possible to avoid use of canvas i.e. decode/encode image without canvas?

#### Screenshots
![2020-02-12-195635_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367934-fe1ce980-4dd2-11ea-8c6c-e714e97858fa.png)
![2020-02-12-195657_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367940-0117da00-4dd3-11ea-9058-6c9cb07f71fe.png)
![2020-02-12-195704_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367952-037a3400-4dd3-11ea-958e-fd0b46e845c7.png)
![2020-02-12-195959_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367958-06752480-4dd3-11ea-8c09-ca5a5eeed3ad.png)
![2020-02-12-200009_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367963-08d77e80-4dd3-11ea-861f-fa8c3f0493d9.png)
![2020-02-12-200014_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367966-0b39d880-4dd3-11ea-8b8a-18bd0569f644.png)
![2020-02-12-200127_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367976-0e34c900-4dd3-11ea-8065-4bfbe973dd4c.png)
![2020-02-12-195626_1440x900_scrot](https://user-images.githubusercontent.com/4147765/74367923-fb21f900-4dd2-11ea-95e6-e766e00752a0.png)

**Comment by elisbyberi** [comment]
Also, it does work as advertised without using "alpha channel".

**Comment by puzrin** [comment]
14.04 is about to eol. Can you try in 18.04?

**Comment by puzrin** [comment]
> Also, it does work as advertised without using "alpha channel".

Alpha is specific thing, with side effects, disabled by default. If your primary goal is to resize "jpegs" - don't enable alpha.

**Comment by elisbyberi** [comment]
Yes, my only goal is to resize jpegs.

Thank you for quick reply.
