### ISSUE TITLE
The ImageBitmap could not be allocated.

### ISSUE THREAD

**Issue by WeiRu1016** [nodeca/pica#190]
chrome version: 81.0.4044.113

pica.resize(originImg, canvas)
some picture error:
DOMException: Failed to execute 'createImageBitmap' on 'Window': The ImageBitmap could not be allocated.

but use canvas, pica.resize(originCanvas, canvse) is success

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/master/index.js#L464

Could you add here

```js
.cach(e) {
  return null;
}
```

then rebuild dist and tell me result

**Comment by WeiRu1016** [comment]
@puzrin this is ok

**Comment by puzrin** [comment]
No ideas, how `createImageBitmap()` can exist but fail to execute.

**Comment by puzrin** [comment]
Published fix. Thanks for your help!
