### ISSUE TITLE
pica 6 breaking browserify build with browser-pack-flat plugin

### ISSUE THREAD

**Issue by greghuc** [nodeca/pica#197]
Hi there,

On upgrading to pica 6 (from 5.3) I am seeing "Uncaught ReferenceError: require is not defined" on my production browserify build. I have tracked the problem to [browser-pack-flat](https://github.com/goto-bus-stop/browser-pack-flat), which is used by [tinyify](https://github.com/browserify/tinyify) to minify the build.

[browser-pack-flat](https://github.com/goto-bus-stop/browser-pack-flat) says it "rewrites require() calls to simple variable assignments. If a module wraps require() somehow it probably will not work. In practice this is quite rare.".

Could you please explain what changed with the browserify build in pica 6, and whether it is rewriting require calls? Is this a hack? I am wondering whether there is an alternative approach to the recent changes that would fix this new ReferenceError.

I can actually avoid the ReferenceError by configuring [tinyify](https://github.com/browserify/tinyify) not to use [browser-pack-flat](https://github.com/goto-bus-stop/browser-pack-flat), but it does mean that the build files will be slightly larger.

And thanks again for pica :-)

Greg

**Comment by puzrin** [comment]
See https://github.com/nodeca/pica/commit/d34e1db9669adf7087f590f8d9dde532c9b51feb

It now uses "compiled" file as main entry, and derequire to allow browserify external packages.

**Comment by greghuc** [comment]
OK thanks - I've noted that pica is breaking with browser-pack-flat at: https://github.com/goto-bus-stop/browser-pack-flat/issues/39

**Comment by puzrin** [comment]
I think, you need report to appropriate repos, this is not pica issue.

**Comment by greghuc** [comment]
Agreed, and thanks for the quick reply. Greg
