### ISSUE TITLE
iOS & Canvas Garbage Collection

### ISSUE THREAD

**Issue by sandstrom** [nodeca/pica#199]
I noticed this iOS issue, which mentions that canvas garbage collection doesn't work unless canvas width/height it set to 0 after use.

https://bugs.webkit.org/show_bug.cgi?id=195325

I'm not saying this is something that should be implemented, but I'm curious if you've heard about crash issues when using Pica on iOS? If so, I just wanted to mention that this *may* be the reason.

**Comment by puzrin** [comment]
SO ref: https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12

I don't remember such issues. That's strange.

**Comment by sandstrom** [comment]
Not something that needs to be tackled, necessarily. I can see the downside of trying to patch a whole we don't know exist, or can't easily verify exist.

But just wanted to put this out here, since it may be relevant.

**Comment by sandstrom** [comment]
@puzrin Wow, that was quick 😄
