### ISSUE TITLE
image corruption on Chrome when not using alpha (jpeg)

### ISSUE THREAD

**Issue by gregorymaertens** [nodeca/pica#203]
Hello,

the following image is corrupted when using Chrome (Version 86.0.4240.183 (Official Build) (x86_64)). Ok on Safari (Version 14.0 (15610.1.28.1.9, 15610)) and Firefox too (82.0.3 (64-bit)).

![Arte-primitiva-el-1-950x701](https://user-images.githubusercontent.com/1636112/99814715-a5406580-2b49-11eb-874a-f540963b05c1.jpg)

While investigating this issue I have noticed that setting alpha: true in the options fixes the issue.
Is it expected? 

You can see with the demo app the pica resize is all black (only in Chrome, ok in Safari, Firefox). 

![Screen Shot 2020-11-20 at 16 01 00](https://user-images.githubusercontent.com/1636112/99814793-c30dca80-2b49-11eb-9ca3-a374df00e262.png)

Sometime the image is corrupted like so:
![Screen Shot 2020-11-20 at 16 07 15](https://user-images.githubusercontent.com/1636112/99815370-7b3b7300-2b4a-11eb-82c1-982d31412737.png)

**Comment by puzrin** [comment]
I can not reproduce. Can you attach image as zip? Is it PNG?

**Comment by gregorymaertens** [comment]
it's a jpg
[Arte-primitiva-el-1-950x701.jpg.zip](https://github.com/nodeca/pica/files/5574580/Arte-primitiva-el-1-950x701.jpg.zip)

**Comment by puzrin** [comment]
IMO that's something Chrome version or hardware specific. I tried demo with Chrome 87.0.4280.66 on Ubuntu, and still could not reproduce problem (but i belive you have it).

They break something from time to time, and problem self-fix in next versions. Pica does no use anything special in js api.

**Comment by DanielStout5** [comment]
I experienced this same issue - setting alpha:true seems to fix it.

The issue is only present for very specific versions of Chrome.

**Comment by boberbober** [comment]
Same issue on MacOS Chrome version 93.0.4567.0

When alpha is set to false I get random black rectangular splats. Attached example input file was JPG so no alpha channel.

They appear randomly on different images but always in the same spot for the same image. Seen here on the right side:

![a1aa16e3-f7e6-4ba5-afa8-d1364c0b3d58](https://user-images.githubusercontent.com/1340952/124716067-3d068e80-df36-11eb-9486-4c666f6555ef.jpeg)

**Comment by puzrin** [comment]
Try v9. It has fixes for transparency and does not use `.alpha` option anymore.
