### ISSUE TITLE
Offer option to resize to maximum width or height

### ISSUE THREAD

**Issue by panabee** [nodeca/pica#204]
Thanks for this amazing software.

Preserving quality is essential when resizing our images, so we are interested in using this.

Have you considered a feature where people don't specify a destination canvas, but instead define the target dimensions (including a max width or max height) and receive a promise result?

This would be useful because users don't need separate operations to (1) ascertain the source image size; (2) compute destination size while preserving aspect ratio; and (3) create a separate canavs element.

Ideally, it would work similar to https://github.com/calvintwr/blitz-hermite-resize: 

```
blitz({
    source: DOM Image/DOM Canvas/jQuery/DataURL/File,
    width: 400,
    height: 600
}).then(output => {
    // handle output
}).catch(error => {
    // handle error
})

```

**Comment by puzrin** [comment]
I'm not interested to mix high level and low level apis in single package. For files there is https://github.com/nodeca/image-blob-reduce.

**Comment by panabee** [comment]
Thanks so much for the quick reply! Will try it out.
