### ISSUE TITLE
Gamma correction?

### ISSUE THREAD

**Issue by jbarth-ubhd** [nodeca/pica#205]
would it possible to add gamma correction for sRGB before/after resize?

I think even if it is not possible to get Display profile information in browser, doing to-linear before and to-sRGB after resizing is better than skipping this steps.

Test image: https://digi.ub.uni-heidelberg.de/diglitData/image/testjbx/1/x.jpg

**Comment by puzrin** [comment]
Pica works with RAW data. You can add pre/post processing as you wish.
