### ISSUE TITLE
Outputs an SVG file

### ISSUE THREAD

**Issue by Namchee** [nodeca/pica#206]
I'm trying to resize an image using pica and output it to an SVG file using `toBlob` with `mimeType: image/svg+xml`. However, it seems that the generated file is unreadable since it's binary formatted. Here's the generated SVG in question:

[icon.zip](https://github.com/nodeca/pica/files/6268873/icon.zip)

Does pica actually support SVG outputs?

**Comment by puzrin** [comment]
This is raster library. Vectors processing is out of scope.
