### ISSUE TITLE
Trying to use in semi-realtime scenario with webworker, but "processTile" runs in main thread and is expensive.

### ISSUE THREAD

**Issue by Giwayume** [nodeca/pica#207]
The [processTile()](https://github.com/nodeca/pica/blob/master/index.js#L352) function runs in the main thread (blocking), and in many browser/device combinations it seems to be fast enough for realtime use. However I've run into some cases where it can take over 100ms to run `processTile()` which is unacceptable lag if I'm running pica on a zoom input handler for example.

I've noticed on a device where it runs slow I can set "concurrency" to 1 and `processTile()` won't hang up the main thread so much, but I don't want to hamper all devices by making this a global setting for everything.

I'd like to test the performance at runtime and adjust the "concurrency" value accordingly, however I don't have any visibility into how long this `processTile()` function takes on the main thread. The Promise returned from `resize(to, from, options)` resolves after both the `processTile()` synchronous work as well as the web worker work completes.

I'm looking to either have to ability to get some programmatic insight into how long each part of the pica resize takes so I can adjust parameters as needed, or alternatively have some new configuration in pica that adjusts concurrency automatically based on how long `processTile()` took the last time it ran. In my case it's better if the overall resize takes more time so long as it minimizes the time spent processing in the main thread so it's not freezing the browser window.

**Comment by puzrin** [comment]
Unstable part is webworker creation. You can increase idle timeout to keep workers on.

https://github.com/nodeca/pica/blob/master/lib/pool.js#L15

https://github.com/nodeca/pica#new-picaconfig

**Comment by Giwayume** [comment]
@puzrin That isn't what I'm experiencing. Doesn't matter if I set idle to Infinity, it's resizing a very large image and the chunking portion of that process is taking time.

**Comment by Giwayume** [comment]
This line is giving bad performance in this case, can you please not be so quick to close?

https://github.com/nodeca/pica/blob/master/index.js#L362

**Comment by Giwayume** [comment]
50ms just to get the image data. That is why I need to have a way to measure this.

![image](https://user-images.githubusercontent.com/4075314/116329783-112e9600-a79a-11eb-9c6f-d8cfa24e290c.png)

**Comment by Giwayume** [comment]
The invokeResize method that creates the workers is very fast in this case. It has nothing to do with pooling.

![image](https://user-images.githubusercontent.com/4075314/116330066-b5184180-a79a-11eb-9e3d-a2a6c30052bc.png)

**Comment by puzrin** [comment]
If problem is with get/set canvas data speed, you can try put whole pica to webworker, see https://github.com/nodeca/pica/pull/198. That requires some work, but doable.

**Comment by puzrin** [comment]
Another option is to patch pica, and transfer [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) to webworker and back, when supported. Then bitmap extraction will happen in webworker. And if it's narrow place, that should help.

If that helps for you case, i can include changes to upstream.

**Comment by Giwayume** [comment]
Unfortunately OffscreenCanvas only has support in Chromium-based browsers, Safari hasn't even attempted the API and Firefox has it locked away under a feature flag for the last 5 years.

It would be easier for now if I had a way to detect that the script is bogging down the main thread so I can determine what to do with it, even if I need to disable it for graceful degredation.

**Comment by puzrin** [comment]
I can discuss only concrete proposals, when implementation details are known.

**Comment by Giwayume** [comment]
I don't know the best API for this since unfortunately promises only return one argument. It's not pretty, but user can pass an empty "timings" object into the options of `pica.resize()` and resize function can fill in the number of milliseconds each section takes in that object. That is good enough for my needs.

```
const timings = {};

pica.resize(fromCanvas, toCanvas, {
    timings
}).then((canvas) => {
    console.log(timings.calculateTiles); // https://github.com/nodeca/pica/blob/master/index.js#L495-L518
});
```

In this example lines 495 - 518 are measured with the difference of `window.performance.now()` and that number is set as the `calculateTiles` variable on the timings object that's passed in.

**Comment by puzrin** [comment]
Try to create working commit in fork, i still not understand what exactly are you going to measure.

With high probability, i could expose those small function as public pica methods, and you will be able to override some with your benchmarking patches. IMO that will be flexible, and will not poison public api with uncertain features. But i need to see working code first for sure.

**Comment by Giwayume** [comment]
^ this is an implementation of what I discussed. If you think the same thing can be accomplished with overrides.
