### ISSUE TITLE
Corrupted image in Chrome or Opera

### ISSUE THREAD

**Issue by zdila** [nodeca/pica#211]
Please ungzip the attached testcase, open `testcase.html` in Google Chrome (mine is currently Version 91.0.4472.101 (Official Build) (64-bit) on Debian Linux) and select attached image. After I select it I see it corrupted. I can reproduce it with Pica 7. With the latest Pica 6 it is OK.

[testcase.tar.gz](https://github.com/nodeca/pica/files/6643430/testcase.tar.gz)

Corrupted result:
![image](https://user-images.githubusercontent.com/636095/121798533-434f6680-cc27-11eb-8aec-a8b77179da98.png)

**Comment by rlidwka** [comment]
This is probably a chrome issue with createImageBitmap, see test case here:
[cib-test.zip](https://github.com/nodeca/pica/files/6663918/cib-test.zip)

I've opened a bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=1220671

**Comment by puzrin** [comment]
Note. Anyway, chrome & FF provide different results. Even when corruption fixed, that will stay unuseable for images with orientation..

**Comment by rlidwka** [comment]
Fixed by adding feature test for this specific chromium behavior.
