### ISSUE TITLE
`cib` works even it's disabled by default

### ISSUE THREAD

**Issue by iharMikailau** [nodeca/pica#214]
It looks like `cib` isn't really disabled by default. Resizing is faster if ImageBitmap = undefined and if rewrite createImageBitmap with simple console.log  we can get canvas and image.

**Comment by puzrin** [comment]
You can attach logger to pica (as in demo), and see details how resize happens. If you declare problem - more trusted proofs required.

**Comment by iharMikailau** [comment]
https://github.com/nodeca/pica/blob/9baefdfce8481b66aa7a8d1473f31db9d538ac29/dist/pica.js#L1905
This action isn't reachable.
