### ISSUE TITLE
Understanding Unsharp algorithm 

### ISSUE THREAD

**Issue by jardakotesovec** [nodeca/pica#22]
Hi,
just looking into your unsharp algorithm and I got lost in last step. Could you explain me one thing.
I assume that you implement this formula `USM(O) = O + (2 * (Amount / 100) * (O - GB))`, right?

What puzzle me is that you are using multiplication [`(c * corr)`](https://github.com/nodeca/pica/blob/master/lib/pure/unsharp.js#L76) for the correction and not addition as the formula above suggests. Is that intention? Maybe its some optimization that I don't understand :-).

Thank you for hint!

**Comment by puzrin** [comment]
I don't remember. Should be some kind of scopes recombination. Anyway, that math is not fast and quality is not recommended for production. Need rewrite with HSL lightness to not clamp channels.
