### ISSUE TITLE
[Feature Request] Save Transparency as White When Resizing as JPG

### ISSUE THREAD

**Issue by jlukic** [nodeca/pica#221]
Thanks for the wonderful project, the webassembly usage is one of the few I've seen in open-source like this and quite brilliant.

### Feature Request 

Modify default behavior for `alpha: false` to squash transparencies to white instead of black, or provide a configuration for how to render alpha layers when resizing to non-alpha format like jpg. 

### Use Case

When you have websites that support image uploads, often times you want to support a variety of image formats like `png` and `gif` for uploads, but want the final results to be without alpha layers by removing them in a reasonable way for display. For example when allowing user avatar uploads.

### Current Behavior

Resize an image with transparency like 
<img width="234" alt="apis" src="https://user-images.githubusercontent.com/23123/138720887-46209177-bb82-4fdb-9de7-80cdb4301148.png">

Current Behavior (Squashes to Black)
![vzH8puuCybTuTdQdv](https://user-images.githubusercontent.com/23123/138720934-27a15ffb-62a4-4122-b5bf-e10af39c76a9.jpg)

Requested Behavior (Squash transparency to white)
![white](https://user-images.githubusercontent.com/23123/138721437-224dc27a-11f6-4c39-9e6b-19c60eb95795.jpg)

**Comment by puzrin** [comment]
That's out of scope. In v9 you have canvas output with correct alpha channel. After resize you can apply any background you wish via canvas api.
