### ISSUE TITLE
Tile artefacts in Chrome (when OffscreenCanvas used)

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#223]
Ref: https://github.com/nodeca/pica/issues/219#issuecomment-975096983

In Chrome test image shows defects on tile's borders, when webworked used.

Workaround:

https://github.com/nodeca/pica/blob/384784f2c27d0eeafabe95604bf1291f1d6e9277/lib/worker.js#L33

If force return typed array, defect disappears.

**Comment by j-p-c** [comment]
A test image that showed the artifacts is [here](http://johncostella.com/pica-chrome-grate.png).
