### ISSUE TITLE
Large potential performance boost with implementation of WebGPU?

### ISSUE THREAD

**Issue by octopushugger** [nodeca/pica#227]
I started looking into the pica code to see what might need to be modified to support WebGPU but I'm a JS noob and don't understand a lot of it. (I don't even know how to run the project aside from the all-in-one js file)

How much do you think pica would benefit from WebGPU and do you have any plans for its implementation? 

If you think it would speed up things a lot but don't have plans for it I might come back to this in the future after learning more JavaScript.

**Comment by puzrin** [comment]
There were no volunteers, able to guarantee stable result & binary equal to other implementations. We tried to implement webgl support, but it was dropped, finally (still can be found in far history).

If anyone wish to add such support, and can provide appropriate quality - PR welcome.
