### ISSUE TITLE
How to resize with .resizeBuffer?

### ISSUE THREAD

**Issue by avalanche1** [nodeca/pica#23]
Hi @puzrin !
Can I select an image from disk, resize it in memory somehow and then put into the final canvas, instead of using an intermediary canvas as source?
I don't really understand `.resizeBuffer`, Uint8Array and how to work with it...

**Comment by puzrin** [comment]
.resizeBuffer is low level math to work with RGBA bitmaps [ r1, g1, b1, a1, r2, g2, b2, a2, ...].

You need decompress jpg / png / ... first to use it.

**Comment by avalanche1** [comment]
Err.. than I don't know if I should even use it, humph..
Could you suggest the most efficient way to use pica for my task:
I have a page which allows users to upload any-sized image and then generates a fixed-size preview and thumbnail.
I'd like the resizing to be done client-side before uploading to my server.

**Comment by puzrin** [comment]
I short - canvas is the only simple way for you to load image.

**Comment by avalanche1** [comment]
Ok, thx!

**Comment by avalanche1** [comment]
btw, is there a way I can use pica as a client-side lib only? my build process doesn't allow for npm packages

**Comment by puzrin** [comment]
See install section. It's available via bower

**Comment by puzrin** [comment]
I've updated readme with info about image <-> canvas conversion. The rest can be found in google & at stackoverflow.

**Comment by avalanche1** [comment]
Finally managed to put it all together)
Speed and quality are awesome!
**Спасибо огромное, Виталий!**
