### ISSUE TITLE
Black canvas on resize

### ISSUE THREAD

**Issue by maxdesmo** [nodeca/pica#26]
This module creates very good quality images. However, if i try to resize an image with an original width between 4000px and ~5000px, i get a black canvas.

Here are a couple of sample images from flickr (choose original size) 
https://www.flickr.com/photos/lens-cap/20694512128/sizes/l                 (4587 x 2580)
https://www.flickr.com/photos/124832301@N07/20886152241/sizes/l   (5075 x 3247)

It doesn't matter what width i try to resize it too.

**Comment by puzrin** [comment]
Works with demo. I think, you have problem with loading initial image into canvas, due iphone / security / other restrictions. That's out if this lib responsibility. It eats canvas / array, and returns canvas / array.

**Comment by pmstss** [comment]
@maxdesmo, perhaps it's max canvas size browser specific issue, see http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

**Comment by maxdesmo** [comment]
@puzrin You're correct, the original canvas is black. I was re-sizing hundreds of images with different sizes with no issues, so i didn't think of the obvious. I'll use the demo to verify in the future. I'll close the bug. Thanks for the quick reply

**Comment by maxdesmo** [comment]
@puzrin FYI, it appears to be an issue with Chrome.

**Comment by puzrin** [comment]
Which one? There are lot of those: mobile / desktop / dev build / OS / ...

**Comment by maxdesmo** [comment]
Google Chrome Desktop Version 44.0.2403.157 (64-bit) on Mac OS X 10.10.4

**Comment by puzrin** [comment]
For info: Chromium 44.0.2403.89 Ubuntu 14.04 (64-bit) is ok with demo and images from first post. No OSX to check.
