### ISSUE TITLE
Black background when resizing transparent png

### ISSUE THREAD

**Issue by antoineheb** [nodeca/pica#27]
Hi,

We are using pica and it's great!

However, we are experiencing an unwanted behavior when resizing PNG images with transparent backgrounds.

I have attached two images.

You can reproduce on your demo page.

Thanks!

![mailsquad](https://cloud.githubusercontent.com/assets/5523400/9970462/5033dac0-5e23-11e5-9b9f-298ace297a12.png)

![gray-twitter-96](https://cloud.githubusercontent.com/assets/5523400/9970470/5ced0da4-5e23-11e5-9012-f36f3e63180c.png)

**Comment by puzrin** [comment]
https://github.com/nodeca/pica#resizebufferoptions-callback

`{ alfa: true }`

**Comment by wichopy** [comment]
Hello! I have png's that are getting grey backgrounds when they have transparent backgrounds. The alpha option has been dropped here https://github.com/nodeca/pica/commit/d8c07a8840fc0e040081f55ef32ce7e01ac75149

Is there an alternative to change the background color? Something I can do inside of canvas?

**Comment by wichopy** [comment]
My mistake! It was CSS making it grey not pica :D
