### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by thokari** [nodeca/pica#29]
Hi, can you give an example, on what to do with the output (from the resizeBuffer() method) ? Specifically, I would like to convert it to something I can directly use with an <img> HTML element.

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/master/index.js#L126

I'd recommend to investigate source code for lib & demo. It's quite small.

**Comment by micky2be** [comment]
Would love to see a bit more details about this API.
What are the optional properties?
Can I leave `width` and `height` empty?
What happen if I set only `toWidth` but not `toHeight`? Is it keeping the ratio?
...

**Comment by puzrin** [comment]
All params without defaults are mandatory.
