### ISSUE TITLE
Problem with resizing images with height > width. Color distortion.

### ISSUE THREAD

**Issue by ilya-slabukarov** [nodeca/pica#32]
Hi,

When resized image has height more than width - color distortion appears in the bottom.
![167_1_1447107097](https://cloud.githubusercontent.com/assets/9151824/11048678/637c4ac2-874a-11e5-894b-3d8b75b26cff.jpg)

Does anyone know how to fix it or where to find a solution?

Thanks.

**Comment by puzrin** [comment]
@a-rodin please take a look, that's in new unsharpen filter (glur is ok)

**Comment by puzrin** [comment]
Fixed. Bug was in mono16 glur https://github.com/nodeca/glur/commit/94d6f188d23216822e742cad6696d4c9facab606

**Comment by ilya-slabukarov** [comment]
Thanks a lot!

Now works as expected.
