### ISSUE TITLE
Experimental, WebGL resize incorrectly renders alpha channel

### ISSUE THREAD

**Issue by piotrpoz** [nodeca/pica#34]
Tested experimental feature WebGL driver which incredibly speeds up rendering (!) even with large images, great work! 
There is a glitch when using alpha channel png images. When WEBGL is turned off it resizes images beautifully: 
<img width="74" alt="correct" src="https://cloud.githubusercontent.com/assets/5487682/12568316/2f4bde5e-c3c5-11e5-86b4-3b951e73032a.png">
After turning WEBGL:
<img width="43" alt="incorrect" src="https://cloud.githubusercontent.com/assets/5487682/12568329/4c0d8042-c3c5-11e5-8c25-989771bbf68a.png">

I've tested this on latest versions of Chrome, Safari, Opera and Firefox on Mac OS X 10.11. Please let me know whether you need any additional information.

The new feature kicks-ass, please improve! :)

**Comment by puzrin** [comment]
Thanks for info! Could you provide a source image, that can be dropped to demo to see live result?

**Comment by puzrin** [comment]
Here are images to reproduce https://github.com/nodeca/pica/issues/27.

Another problem was that demo did not used `{ alpha: true }` option. Updated. But WebGL still does not works well with alpha.

**Comment by piotrpoz** [comment]
Here is a source image (but I think it is less demanding than image posted above), tested with ```{alpha: true}```:

![lge_nexus_5_hammerhead](https://cloud.githubusercontent.com/assets/5487682/12577567/5a6a3184-c41b-11e5-9b0b-3095176996c7.png)

As tested on demo page, the alpha channel is not working either on Box and Lanczos filters. On Hamming filter edges are not smooth (some fair results can be obtained playing with unsharp settings).

**Comment by puzrin** [comment]
Should work now. Note, upscaling in webgl still sucks, but that's another problem. Probably we will disable this (fallback to js), because nobody need it in real world.

If you have a time - try to test new demo. Toggle webgl on/off. May be you will find a good sample images with artefacts.

**Comment by piotrpoz** [comment]
Tested on demo page and used new dist in the project and alpha channel is treated respectively. Great job! Did not find any glitches.

As for upscaling- like you wrote, it is not related with this issue.

**Comment by puzrin** [comment]
Try pica 2.0, it should be better on multicore hardware (without buggy webgl)

**Comment by piotrpoz** [comment]
Hi there!
Sorry for my late reply. I tried pica 2.0.2 on real time rendering and I must say that webgl has incomparable better performance. 
Also, you make take a look at Chrome timeline here. First shows timeline for rendering a movie without webgl:
![nowebgl](https://cloud.githubusercontent.com/assets/5487682/15144259/97b06c26-16ae-11e6-9e68-1461377e7cb9.png)

And this one below shows rendering with webgl:
![webgl](https://cloud.githubusercontent.com/assets/5487682/15144272/a628681c-16ae-11e6-87a8-f4f6288f77ef.png)

Webgl consumes more CPU however it provides more FPS (which is a goal in my project).
