### ISSUE TITLE
Not smooth contours in webgl

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#39]
Load addached image to demo and toggle webgl checkbox on/off. In webgl mode lines become not smooth.

![76253096-c429-11e5-873c-7a3189008ba7](https://cloud.githubusercontent.com/assets/319465/12711372/5aa50cfa-c8d0-11e5-9eed-7a3658df32ba.png)

**Comment by felixbuenemann** [comment]
Here is another [good test image](http://www.rollthepotato.net/%7Ejohn/skin/skin-texture.jpg) from the libvips author. Is has lots of fine hair detail. In WebGL mode in Safari 9.1 there is very heavy aliasing in the hair and on the edge of the blouse.

With WebGL:

![webgl](https://www.dropbox.com/s/l5fknqp4ne14ffz/Screenshot%202016-02-16%2015.58.56.png?dl=1)

Without WebGL:

![no webgl](https://www.dropbox.com/s/c4f6i8170if5f6m/Screenshot%202016-02-16%2015.59.56.png?dl=1)

**Comment by puzrin** [comment]
Yeah, shaders need full rewrite. Especially after added tiler (now in dev branch)

**Comment by puzrin** [comment]
I tend to completely drop webgl support due maintenance difficulties. Also, upcoming webassembly/simd support should provide similar speed benefits.

**Comment by puzrin** [comment]
Closeing - ww support will be depraceted, see #82
