### ISSUE TITLE
Upcoming pica 2.0 changes

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#42]
Pica is currently in process of rewrite. Goals are:

- restrict resource use, to allow more advanced algorythms
  - floating point for intermediate data between horisontal/vertical passes, requires 4x more memory.
  - webgl has restriction for max texture size
- utilize parallel processing, when possible (web workers).

**How will it work:**

- Split image by tiles (512x512...1024x1024), to restrict memory for each step
  - Since result will be inaccurate on edges, each tile will include additional "border" to drop later.
  - according to our experiments, 1024x1024 tile size is optimal for speed. That's 4mb of raw data. If we decide to use floats without interleave, that will require 20mb internal buffers in lanczos filter. Tile size reduce to 512x512 eats 20% of speed.
  - border size:
    - minimal is 3px of destination image * scale (defined by filer window size)
    - maximal depends on required blur radius for unsharp
- Use worker pool for parallel processing.
  - we can detect number of cores via [navigator.hardwareConcurrency](https://wiki.whatwg.org/wiki/Navigator_HW_Concurrency) or set to 2-4 if unknown

**API changes:**

- Drop `resizeBuffer` as useless and breaking data flow. Pica should always use `Canvas` or `Image` for input.
  - this method will be available intarnally, but with changed signature. We now have to pass float scale/offset, to properly locate input/output tiles data.
- Drop WW id exposure, replace with internal ID.
- Restrict max allowed blur radius to 1.0-2.0 for unsharp, because it increase tile border size.
  - Even if we change algorythm to blur image before resize, it will need 0.2-0.5 blur radius
  - Current required blur radius is < 2.0
- Proposed API
  - `.resize(srcCanvas/srcImage, destCanvas, options, callback)` -> taskID
  - `.terminate(taskID)` - for example, if user leave page via ajax and you wish to quickly free resources
  - `.WW`, `.WEBGL`, `.concurrency` - fine tune params if autodetect is not enougth.

**Later**

- Experiment with blur before resize instead of unsharp mask.
  - For small radius direct kernel calculation can be more effective than `glur` + HSL transforms.
- Care about GPU sharpener for webgl resizer.
- Rework webgl resizer to use precalculated filters (as native resizer does).

I cc this issue to all who created important tickets and helped to improve pica. If you have ideas about API improvment - let me know. Also let me know, if you have ideas how to test webgl on multiple mobile devices.

/cc @dene-, @devongovett, @gordyr, @a-rodin, @noomorph.

**Comment by devongovett** [comment]
`resizeBuffer` is super useful in places where canvas is not available, such as web workers, and node. I use it in my [resizer-stream](https://github.com/devongovett/resizer-stream) module, which I use in web workers currently, but also works in node.

**Comment by puzrin** [comment]
@devongovett problem is in effective tiles generation. `.putImageData()` / `.getImageData()` are very ineffective and we should minimize their count. It's much faster to use `canvas.drawImage()` to build regions. Also, webgl requires canvas at input, and it's already supported in FF nightly webworkers.

RGBA buffer resize will be available, but as internal file. If you can't live without it, you will be able to use it as `require(pica/lib/js/resize_array)`. But as i said, using is directly is not effective with some types of resize methods.

**Comment by puzrin** [comment]
@devongovett is it ok, if `resizeBuffer()` will support only "simple" mode, without webworkers / webgl and other adapters? I tend to leave it as legacy method.

PS. going to release soon. See dev branch changes.

**Comment by devongovett** [comment]
Sure. I can run it in a web worker myself.

**Comment by puzrin** [comment]
Closed - architecture questions resolved. The rest moved to #49

**Comment by puzrin** [comment]
Released 2.0. Enjoy!
