### ISSUE TITLE
Fixture test doesn't compare images exactly

### ISSUE THREAD

**Issue by a-rodin** [nodeca/pica#47]
The fixture test uses [node-resamble](https://github.com/lksv/node-resemble.js) which performs fuzzy comparison of images instead of exact pixel-to-pixel checking. 

It looks like exact pixel-to-pixel comparison is more correct in this test, so we have to do something with it.

**Comment by puzrin** [comment]
https://github.com/mapbox/pixelmatch

Seems that's more fresh and has all we need

**Comment by a-rodin** [comment]
I agree, it looks pretty good.
