### ISSUE TITLE
Any way to resize images from blob?

### ISSUE THREAD

**Issue by tastemeru** [nodeca/pica#48]
Hi, it seems as pica a great library, but it really complex to dive in for newbies like me. What steps I should to do to resize image from a form? I get image as blob and what then?  Put this image to a hidden canvas, then resize it with pica to another hidden canvas? Is there some simply way to resize it with pica?

**Comment by puzrin** [comment]
> Put this image to a hidden canvas, then resize it with pica to another hidden canvas?

Yes.

> Is there some simply way to resize it with pica?

That's a low level library, not jquery plugin :)

I think, digging code of demo can help https://github.com/nodeca/pica/blob/1.1.1/demo/index.js

**Comment by puzrin** [comment]
I'm sure you will succeed with some patience. If you have a time after - may be you could give advice how to improve docs.
