### ISSUE TITLE
Some images are repeat during pica.resize

### ISSUE THREAD

**Issue by Akta3d** [nodeca/pica#50]
![rondanyone](https://cloud.githubusercontent.com/assets/6841666/14075935/b462125e-f4dd-11e5-9b42-bb244d1be5be.png)

In demo web page if import this picture we cann see duplicates.
If use webgl, no duplicates

**Comment by puzrin** [comment]
Confirmed. 1.1.1 has no such bug. Probably, regression in tiler.

**Comment by puzrin** [comment]
Should be fixed, but i encourage to test more images with transparency.

**Comment by Akta3d** [comment]
Ok, Thanks for your reactivity.
I have test more 50 images with transparency, and all is good for me.
Thanks
