### ISSUE TITLE
On import image with alpha channel can we choose the replacement color of alpha

### ISSUE THREAD

**Issue by Akta3d** [nodeca/pica#51]
If I use pica with alpha = false and set an entry picture with alpha channel, transparent pixel are convert to black.
Is it possible to set a custom color for this alpha transparent pixels ?

**Comment by puzrin** [comment]
That's not possible. I'd say, you need convert image to canvas with alpha (pica do it), and then do additional step to replace transparency. I'm not sure it's good idea to include such step to pica.

**Comment by Akta3d** [comment]
ok, thanks for your response. 
I add a next step after pica process.
