### ISSUE TITLE
Resize with image as a source

### ISSUE THREAD

**Issue by martinsookael** [nodeca/pica#52]
Thank you for the library!

Just a quick question - the Readme states, that you can "Resize image from one canvas (or image) to another". Is there really a possibility to resize only the image or do we always need to involve the canvas for input? 

Currently I got it working like this:
1. get image from form and convert to blob. 
2. load the blob to a new Image() and when it's loaded put it to canvas.
3. using resizeCanvas resize the canvas to another canvas with the proper size. 

(and don't we loose the quality if we still use the canvas as a source?)

**Comment by puzrin** [comment]
JS allows image pixels access via canvas only (or via manual decode). But input param `from` can be image too. Output is always canvas.
