### ISSUE TITLE
Animated GIFs

### ISSUE THREAD

**Issue by klebervirgilio** [nodeca/pica#53]
Hi,

I've been trying to find a javascript library capable of resize an animated gif in the browser and preserve the animation. Pica does not seem to have the _preserve animation_ ability. 

Wondering, is it something doable? 

If so, Could you guys show me how I can contribute to pica and implement that feature?

Thanks!

**Comment by puzrin** [comment]
Pica works at lower level and don't know anything about image formats. You need somehow to split gif to frames, resize each frame and reassemble result back. That's out of this project goal.
