### ISSUE TITLE
Blob URL leak

### ISSUE THREAD

**Issue by fuerte656** [nodeca/pica#55]
We have encountered a problem with Pica when processing large amounts of images (i.e. 1000+). When we resize multiple images through Pica, eventually it stops working, and when we look into the Network tab of the Developer Tools (on Chrome), we can see a corrupted Blob URL (empty).

I have taken a look at the Pica's source code and found that Pica creates Blob URLs using the `URL.createObjectUrl` to pass them to the worker constructor. There is a code like this: 

```
    return new Worker(URL.createObjectURL(
        new Blob([src], { type: 'text/javascript' })
    ));
```

The documentation for `URL.createObjectURL` says that you have to release these URLs when they are no longer needed using the `URL.revokeObjectURL`:

https://developer.mozilla.org/en/docs/Web/API/URL/createObjectURL

However, in the code above, the created Blob URL is not released and apparently gets orphaned. As a result, when too many Blob URLs are created, the `URL.createObjectURL` starts failing (perhaps, it reaches some browser's limit for a number of Blob URLs). 

I was going to patch Pica to save a reference to the Blob URL and revoke it when the worker is terminated, but I have updated to 2.0.2 and found out that the `resizeBuffer` method does not use workers anymore. So this update works for me, but you may want to fix it for the `resizeCanvas` method.

**Comment by puzrin** [comment]
https://github.com/substack/webworkify/blob/v1.2.1/index.js#L66

Seems browserified version was assembled with old version of `webforkify`.

**Comment by puzrin** [comment]
Fixed in 2.0.3, thanks for report!

**Comment by puzrin** [comment]
@fuerte656 BTW, could you explain your use case for `resizeBuffer`? I tended to deprecate it but left for compatibility with minimal features.

**Comment by fuerte656** [comment]
I use Pica since version 1.0.7
And has researched source code, and found that resizeCanvas is just wrapping around resizeBufer. Then I have implemented splitting canvas to  tiles and running it multi-thread.
At this moment, i have this code working with resizeBuffer.

**Comment by puzrin** [comment]
Thanks for info.

**Comment by puzrin** [comment]
https://github.com/substack/webworkify/issues/26 seems changes were rolled back due IE Edge bug. Anyway, webworers are cached for several seconds, and intensive use will not create a bulk of leaked objects.

I think, problem will be self-resolved in future
