### ISSUE TITLE
Upgrade browserify bundle to latest webworkify to get around an IE Edge web worker issue

### ISSUE THREAD

**Issue by plainview** [nodeca/pica#56]
Webworkify 1.2.1 has a known issue in IE Edge that prevents web workers from emitting messages (see here: https://github.com/substack/webworkify/issues/26).

We ran into this issue when using the latest browserified pica.js package, which uses webworkify 1.2.1.  The issue has been tackled in a minor version bump on Webworkify (1.3.0) and could be included in Pica by upgrading.  I think it might require some changes in Pica too since the library will now need to explicitly revoke the worker URLs to avoid leaking them.

**Comment by puzrin** [comment]
Thanks for info, done.
