### ISSUE TITLE
Memory leak issue 

### ISSUE THREAD

**Issue by carolSequeira** [nodeca/pica#58]
We are using pica for resizing images within our project. We noticed that there is a memory leak issue happening with this component and it was observed that it was happening in the component used to create the webworker (webworkify).
This component create a blob object of the source code then it will make a reference of this object using the createObjectURL function and pass it to a webworker.
This newly create ObjectURL is never released in the webworkify componant . It should use the function window.URL.revokeObjectURL in order to do so to fix this. Please suggest

**Comment by puzrin** [comment]
See #55, #56, #57, with refers to webworkify. Last attemt to do quick fix failed. If you know proper method - let me know.
