### ISSUE TITLE
SCRIPT5022: IndexSizeError in IE11 when using webworkers.

### ISSUE THREAD

**Issue by bbrala** [nodeca/pica#61]
I sometimes get an error with IE11, it kind of depends on the image. I try to write a set of 8 images to another canvas. This is done after resizing the images with pica.  It works perfectly in chrome and firefox, but for IE11 it only works if i use WebGL.

The error is in resize_js_ww
``
    fromTileCtx.drawImage(from, tile.x, tile.y, tile.width, tile.height, 0, 0, tile.width, tile.height);
``

I'm having a hard time debugging this. It feel like it is trying to create an image larger than the canvas mabye? 

I tried to make a fiddle to show the problem, but i have a hard time isolating the problem.

**Comment by puzrin** [comment]
No idea. There were resent issues about release ObjectURL in IE, but nobody of those people reported problem with canvases.

You can completely disable webworkers for debug, to have everything in one thread. Let me know when details available. Also note, WebGL is buggy and not recommended for production use.

**Comment by bbrala** [comment]
Yeah I noticed the mention of WebGL being buggy. I'll have a look what happens if i remove the webworker.

**Comment by bbrala** [comment]
Guess i'll check tomorrow. Npm is being very very slow :)

**Comment by bbrala** [comment]
Well... It seems to be rounding somewhere. When I use a portrait i need to make height one less (sometimes), when landscape width (sometimes).
``fromTileCtx.drawImage(from, tile.x, tile.y, tile.width - 1, tile.height - 1, 0, 0, tile.width, tile.height);``

I've delved a little deeper and found the moment it goes wrong is when generating the tiles. It ends up with a tile that is a pixel larger thank it should be. Probably something with rounding with ``Math.ceil(toTileWidth / scaleX)``.

I made a fix which checks for that case by using the options object.

```js
width: Math.min(options.width, Math.ceil(toTileWidth / scaleX)),
height: Math.min(options.height, Math.ceil(toTileHeight / scaleY))
```

I'll send a PR your way.

**Comment by puzrin** [comment]
Hm... interesting. In this case bug should be reproducible with the same image.

As far as i remember, we calculate integer destination tiles first, and then build reverse projection to source with floating precision (integer tile size + floating compensation for convolution filters).

**Comment by bbrala** [comment]
Perhaps it is also for you. The data of what i do:

``previewLogo`` is an ``new Image()`` with src: https://drive.google.com/file/d/0B8USuoY3FSfYRGNaMWNTZTctV1U/view?usp=sharing

``tmpCanvas`` is a canvas element (created with js)
``width: 140``
``height: 36``
```js
pica.resizeCanvas(previewLogo, tmpCanvas, {
      alpha: true,
      quality: 3,
      unsharpAmount: 75
    }, function () {});
  };

**Comment by bbrala** [comment]
Sorry, i forgot something, i resize the canvas to  ``width="21" height="36"`` so it keeps aspect ratio, which is calculated from the image size.

So i`m trying to render the image into a canvas of `` width="21" height="36"``. Forgot about that piece of code :)

**Comment by bbrala** [comment]
Could you build a new release anytime soon?

**Comment by puzrin** [comment]
Wouldn't it be better to write `almostFloor(x)` and `almostCeil(x)` instead of calling `floor(fix(x))` ?

`floor(fix(x))` looks a bit confusing in my eyes, because `fix` does not necessary "fix something broken".

**Comment by puzrin** [comment]
@bbrala how urgent is it? Need to polish things a bit

**Comment by bbrala** [comment]
I will include a branch for now. The client I am using this for wants to go live in 2 weeks. But I could use a fork as source for a while. So no big hurry.

**Comment by puzrin** [comment]
It will be released today or tomorrow. Just need to document algorythm properly (and may be improve code "understandability").

**Comment by puzrin** [comment]
Released, thanks for your help!

**Comment by bbrala** [comment]
Thanks for being so responsive! Will change my source back to this again.
