### ISSUE TITLE
Consider JS SIMD functions and types

### ISSUE THREAD

**Issue by homm** [nodeca/pica#65]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/SIMD

It's already implemented in some browsers and gives promising results:

https://habrahabr.ru/post/308696/
http://corey-maler.github.io/simdBenchmark/index.html

**Comment by puzrin** [comment]
I know about SIMD (and about WebAssembly), but it's not available in regular builds anywhere, only in nightly/dev. That stays for a long time, and i prefer to not create issues in advance.

Let's close this issue as something without known deadlines. Of cause, is someone decide to make PR, that will be accepted without look at browsers state.

**Comment by puzrin** [comment]
Just for your info. SIMD is still not supported in browsers, and even beta was dropped from v8 :(.

We already experimented with WebAssembly https://github.com/puzrin/convolve-wasm, but it also does not support SIMD yet and now gives only 20% speedup over JS.
