### ISSUE TITLE
Pica not bundling properly with: ES6 imports/WebPack/RequireJS

### ISSUE THREAD

**Issue by Tarpsvo** [nodeca/pica#70]
Hey.

Title states the issue, and the error I receive was the following:

```
Error processing templates Path must be a string. Received { './lib/js/create_canvas.js': './lib/js/create_canvas_browser.js' }
-----------------------
[TypeError: Path must be a string. Received { './lib/js/create_canvas.js': './lib/js/create_canvas_browser.js' }]
-----------------------
```

Fixed it by redirecting the `browser` field in the `package.json` file to the final product:
```
"browser": "./dist/pica.min.js"
```

I am unaware of the consequences of this change for other bundling options though (SystemJS etc).

**Comment by puzrin** [comment]
This "fix" is invalid.

**Comment by Tarpsvo** [comment]
This fixes WebPack. Can you suggest a solution for both then?

**Comment by puzrin** [comment]
Just require file from dist directly, if you need it. I have no idea what you do with webpack / es6.

**Comment by Tarpsvo** [comment]
After changing the 'browser' parameter, I can just write `import pica from 'pica'`, as expected.

**Comment by Tarpsvo** [comment]
Still does not work. Added 'main' entry point to `package.json` as another plausible fix.

See #72
