### ISSUE TITLE
Question: how to use pica with webpack?

### ISSUE THREAD

**Issue by zdila** [nodeca/pica#73]
If we do `require('pica')` and we compile our app with webpack (`target: 'web'`) then build fails with:

```
ERROR in ./~/pica/lib/resize_webgl.js
Module not found: Error: Cannot resolve module 'fs' in /home/user/myapp/node_modules/pica/lib
resolve module fs in /home/user/myapp/node_modules/pica/lib
  looking for modules in /home/user/myapp/node_modules
    /home/user/myapp/node_modules/fs doesn't exist (module as directory)
    resolve 'file' fs in /home/user/myapp/node_modules
      resolve file
        /home/user/myapp/node_modules/fs doesn't exist
        /home/user/myapp/node_modules/fs.webpack.js doesn't exist
        /home/user/myapp/node_modules/fs.web.js doesn't exist
        /home/user/myapp/node_modules/fs.js doesn't exist
        /home/user/myapp/node_modules/fs.json doesn't exist
[/home/user/myapp/node_modules/fs]
[/home/user/myapp/node_modules/fs]
[/home/user/myapp/node_modules/fs.webpack.js]
[/home/user/myapp/node_modules/fs.web.js]
[/home/user/myapp/node_modules/fs.js]
[/home/user/myapp/node_modules/fs.json]
 @ ./~/pica/lib/resize_webgl.js 14:2-15 16:2-15
```

If we do `require('pica/dist/pica')` then it works but webpack outputs following warning:

```
WARNING in ./~/pica/dist/pica.js
Critical dependencies:
1:505-512 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/pica/dist/pica.js 1:505-512
```

What is the proper way to do it?

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/master/package.json#L33 there is rewrite rule for `browserify`. But i'm not familiar with webpack, probably it requires to define file substitution in other way. Or use `require('pica/dist/pica')` and ignore warning.

If you know how to add webpack support properly - do PR and it will be accepted.

**Comment by zdila** [comment]
Problem was actually https://github.com/nodeca/pica/blob/master/package.json#L29. To make it work with Webpack:

1. `npm install transform-loader --save-dev`
1. `npm install brfs --save-dev`
1. add `{ test: /\.js$/, include: /node_modules\/pica/, loader: 'transform?brfs' }` to Webpack `loaders` config.

If you wish you can put it to README.

**Comment by puzrin** [comment]
Can it be done with adding `webpack.config.js` to pica folder or webpack does not support nested configurations?

**Comment by zdila** [comment]
This feature seems not to be directly in webpack. There is a [package that adds this feature](https://github.com/andreypopp/webpack-package-loaders-plugin) but then there is no benefit of it over the solution I've mentioned because you still need to alter your Webpack configuration.

BTW there is another approach for supporting `browserify` property in Webpack: https://github.com/hughsk/ify-loader. I've tested it and it works as well.

**Comment by puzrin** [comment]
May be, webpack supports any other method out of box to define config for nested package? It's not necessay to make it understand browserify transforms, we could add a separate config.

Also, i could move templates from files to source code. But that will require template strings (and babelify support), to make code easy to read/maintain. Don't know if it will be more easy for webpack, compared with `brfs`.

**Comment by zdila** [comment]
As I mentioned, there is probably no out of box solution for Webpack. Otherwise there would probably be no such project like https://github.com/andreypopp/webpack-package-loaders-plugin. It adds support for `webpack` property.

If I google "brfs webpack" then most of the results mention [transform-loader](https://github.com/webpack/transform-loader).

Also I am no Webpack expert (as Webpack is huge) so maybe this could be a good question for StackOverflow :-).

**Comment by puzrin** [comment]
Ok. Feel free to PR any improvements if you wish (configs, readme info etc). I don't plan to investiagte webpack, but will not reject PR if someone wish to do it right.
