### ISSUE TITLE
Use createImageBitmap if available

### ISSUE THREAD

**Issue by Prinzhorn** [nodeca/pica#75]
https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapFactories/createImageBitmap

I was hoping pica would solve my performance issues, but it does not. Resizing in a web worker is great, but the problem is decoding the image data on the UI thread. My test image is 7200x4800 and 4.5 MB (https://hd.unsplash.com/photo-1414396938948-81a7045e336f).

The UI is blocked for about 700ms due to "Image Decode" triggered by [getImageData](https://github.com/nodeca/pica/blob/672243e22bf2df0496f26aa465165c75dea0d16f/lib/resize_js_ww.js#L75).

![screenshot from 2016-10-19 12 23 16](https://cloud.githubusercontent.com/assets/679144/19515251/ed8b9a2c-95f6-11e6-9d26-4c8444d96b56.png)

Do you think we can use a File/Blob object, pass it to the web worker and decode the image there?

Note: you can not see this on the demo page, because you are rendering the images and the timeline doesn't show "Image Decode" separately but as part of "Composite Layers". If you hide the elements in the demo (display: none) you can see it. For the demo it's unavoidable to have image decoding on the UI thread, as you display the original image. But in the real world you might use pica to resize the image and then upload it, while never displaying the original to the user.

![screenshot from 2016-10-19 12 27 04](https://cloud.githubusercontent.com/assets/679144/19515393/872a15aa-95f7-11e6-83ce-fa14a0a5b42e.png)
![screenshot from 2016-10-19 12 27 30](https://cloud.githubusercontent.com/assets/679144/19515392/8724bcc2-95f7-11e6-88e3-4a0929b9032b.png)

**Comment by Prinzhorn** [comment]
I just realized createImageBitmap has resizing built in and a `resizeQuality` parameter. Sadly only in Chrome, because it would make things SO much easier.

**Comment by puzrin** [comment]
You can call https://github.com/nodeca/pica/blob/master/lib/js/resize_array.js for raw bitmaps, but that will not solve problem "how to decode jpg file".

I don't know if webworker can work with canvas inside to decouple image decoding from main thread.

**Comment by puzrin** [comment]
700ms is not good, but better than nothing :)

**Comment by Prinzhorn** [comment]
> I don't know if webworker can work with canvas inside to decouple image decoding from main thread.

In case of image uploading my source is a File object and not a canvas anyway. I'm using `img.src = createObjectURL(file)` to use it with pica. But you're right, web worker interob might be an issue.

**Comment by Prinzhorn** [comment]
> 700ms is not good, but better than nothing :)

I'm working on a WYSIWYG for image galleries and if you drop 10 of those files into it we're already blocking the browser for 7s :(. But they have to be decoded at some point, the performance issue is not an issue with pica but in general.

**Comment by puzrin** [comment]
> And we could pass the file object directly to the web worker without an intermedia image/canvas.

In this case you will not be able to use multiple cpu cores. Because you can't create tiles until binary data decoded into bitmap.

Also, tiles create indirect limits for memory use (max tile is 1000x1000).

In theory, it would be best to decode only necessary part of image, but that's not easy.

**Comment by Prinzhorn** [comment]
> In this case you will not be able to use multiple cpu cores. Because you can't create tiles until binary data decoded into bitmap.

Just like right now, isn't it? Because currently its decoded on the UI thread and THEN the web workers start doing their work with resizing.

All of this would only make sense though if we can turn an ImageBitmap into an ArrayBuffer or if it implements Transferable. If not, then we'd end up with a lot of memory operations to copy stuff between workers which is bad.

**Comment by Prinzhorn** [comment]
Never mind

> ImageBitmap objects are cloneable objects and transferable objects.

https://html.spec.whatwg.org/multipage/webappapis.html#imagebitmap

**Comment by puzrin** [comment]
In theory, if browser allows, we could:

1. pass blob to worker
2. decode there
3. pass bitmap back (as typed array)
4. continue resize via tiles ~ in the same way like now.

**Comment by puzrin** [comment]
Use of resizeQuality in createImageBitmap is interesting idea. Need to think if we can detect options support or not.

**Comment by Prinzhorn** [comment]
> In theory, if browser allows, we could:
> 
>     pass blob to worker
>     decode there
>     pass bitmap back (as typed array)
>     continue resize via tiles ~ in the same way like now.

That's what I was thinking. But I believe it would make sense as a completely separate project to keep things simple. The pica api would still accept a canvas as source, but we could create this canvas in different ways.

Also one more thing: aren't browsers already capable of decoding JPEGs asynchronously when they're in the document? If so then the problem is that `getImageData` etc. are synchronous and force the browser to decode it right now. Maybe it's possible to decode an Image asynchronously?

**Comment by Prinzhorn** [comment]
Oh well, `createImageBitmap` **is** async, so maybe it does not block? If so, then there's not need for a web worker.

**Comment by Prinzhorn** [comment]
We can take a look at the sources of https://github.com/GoogleChrome/offthread-image

**Comment by puzrin** [comment]
I don't know about async decode. Also note, i have no strong frontend experience. This project was done to train skills in writing fast js math for modern JITs :)

**Comment by puzrin** [comment]
I've started next round and plan to add createImageBitmap & WebAssembly support. Experiments with webassembly already done https://github.com/puzrin/convolve-wasm.

Did you find any issues with createImageBitmap in the past? is `resizeQuality` option supported in chrome?

**Comment by puzrin** [comment]
Done in 3.0.

**Comment by Prinzhorn** [comment]
I haven't used `createImageBitmap` so far. It's awesome how you're pushing the boundaries with pica. Keep up the good work :)

**Comment by puzrin** [comment]
3.0 is in separate branch now, but i plan to release it very soon. See changelog, demo and let me know if you have comments.

**Comment by puzrin** [comment]
Released 3.0, enjoy!

Did not tested in old browsers, but i hope i did not broken anything serious
