### ISSUE TITLE
Electron Support

### ISSUE THREAD

**Issue by McPo** [nodeca/pica#80]
Due to requiring `create_canvas.js` as opposed to `create_canvas_browser.js`. Electron is not supported.

Is there a suggested fix to continue to support Node, Browser and Electron?

**Comment by puzrin** [comment]
Do you use files from `./dist` or not? That's NOT node package. Node is used for development.

**Comment by McPo** [comment]
That solved it.

I was doing
```
import pica from 'pica';
```

however, changing it to:
```
import pica from 'pica/dist/pica';
```
Resolved the issue.

Cheers
