### ISSUE TITLE
ES5-compatible pica version

### ISSUE THREAD

**Issue by taikn** [nodeca/pica#85]
Hey, congrats on the new release! I've noticed you've used some ES6 features in this release, which breaks minification using UglifyJS. I was wondering, if there's a plan to have ES5-compatible version of the pica, or not.

**Comment by puzrin** [comment]
Compiled project is in `/dist` folder, and it's in es5. If you wish to use pica as node module, you need browserify or setup your bundler appropriately. See https://github.com/nodeca/pica#install

**Comment by taikn** [comment]
Ah, sorry must've overseen that, it worked, thanks a lot!
