### ISSUE TITLE
RuntimeError: memory access out of bounds could not be cloned.

### ISSUE THREAD

**Issue by chebum** [nodeca/pica#87]
Faced a regression after upgrading to 3.0.1 from 2.0.8. When scaling images UP, the code fails inside `wasm_instance.exports.convolveHV` with the message above. Everything works when scaling images DOWN.

**Comment by puzrin** [comment]
Wow, it's very strange that upscale works in 2.x. AFAIK, it should not :)

Do you use this functionality or just tested and noticed exception?

**Comment by chebum** [comment]
I tried and it seems to work. Here is a build with 2.0.8: https://myimageresizer.com
For example, if I upload https://myimageresizer.com/assets/large-logo.png and set Fit Width option to 1000, it correctly scales the image up. The same picture crashes with 3.0.1.

**Comment by chebum** [comment]
@puzrin Vitaly, fantastic!

**Comment by puzrin** [comment]
Thanks. But i still don't recomment to use this package for  upscale. At first, it's not intended to and not tested anyhow. At second, upscale should use Mitchel filter, not implemented here.
