### ISSUE TITLE
Pica not resizing

### ISSUE THREAD

**Issue by LoganLehman** [nodeca/pica#90]
Hi,

Since the new update (I rewrote my code to reflect new API), the image doesn't actually resize anymore. It will cut off the corner of the image and make that the 150x150 tile I specified. I am passing the data from an img tag to a canvas, then uploading. 

See my code (truncated without upload logic) here:

                  
```       
                    var imgCropped = el.find('.image-cropped');
                    imgCropped.attr('src', resp);
                    imgCropped.attr('width', viewportWidth)
                    imgCropped.attr('height', viewportHeight)

                    const pica = window.pica({
                        tile: viewportHeight, // Tile width/height. Images are processed
                        // by regions, to restrict peak memory use.

                        features: ['all'], // Control used features. Can be:
                        // [ 'js', 'wasm', 'cib', 'ww' ] or [ 'all' ]
                        // Note, resize via .createImageBitmap() disabled
                        // by default due bad quality.

                        idle: 2000, // Cache timeout, ms. Webworkers create
                        // is not fast. This option allow reuse
                        // webworkers effectively.

                        concurrency: 4 // Max webworkers pool size. Default is
                        // autodetected CPU count, but not more than 4.
                    });

                    pica.resize(imgCropped.get(0),
                        el.find(canvas).get(0), {
                            quality: 3,
                            unsharpAmount: 50,
                            unsharpRadius: 1
                        }).then(result => {

                        var pngData = result.toDataURL();

```

Output: ![user58f6e016c7e2a](https://cloud.githubusercontent.com/assets/1081678/25162806/45a916aa-247a-11e7-92f1-360b4aa9772f.png)

Expected output: ![data-image-jpeg bas](https://cloud.githubusercontent.com/assets/1081678/25162823/62ddf22c-247a-11e7-959f-e8b7d7f97444.jpeg)

Of course, the expected output should be resized to the output...

(and yes, that is a mighty fine dickbutt)

**Comment by LoganLehman** [comment]
@puzrin

**Comment by puzrin** [comment]
1. Remove `features: [ 'all' ]`
2. What browser do you use? Can you reproduce this problem in demo?

**Comment by puzrin** [comment]
Updated example in readme.

**Comment by LoganLehman** [comment]
@puzrin - Removing all of the options and following the readme example worked! thank you

**Comment by puzrin** [comment]
@LoganLehman i still need info about browser/os where issue with enabled 'cib' can be reproduced. Could you tell me?
