### ISSUE TITLE
30MB resize too slow

### ISSUE THREAD

**Issue by pradipvaghasiya** [nodeca/pica#92]
Hi,
First of all thanks for making this library. It certainly give high quality resized images. 
In my website, I am trying to resize 30 MB JPEGs straight from DSLR. 

It is taking 6 to 8 seconds to resize 1 30MB image. is this performance expected or is there any way to make it faster?

I am using 2.0.8 version

**Comment by puzrin** [comment]
Need this details:

- browser/os (try Chrome & FF)
- input width*height / output width*height
- try in 3.0

**Comment by emrecamasuvi** [comment]
Related issue occurred here.
Browser (FF) shows a warning message about slowness.
Chrome stops all interactions, even setInterval/setTimeout events delay due to high cpu usage i guess.

windows 10 / firefox 53.0 (32-bit)
input 12311x8260 output 1610*1080 
pica 3.0.4
pica({ features: [ 'js'] });

**Comment by puzrin** [comment]
@emrecamasuvi that's not related. Do you have reasons to disable webworkers? They add required pauses between tiles.

PS. I guess you tried to add setTimeout in wrong place. Should be patched [here](https://github.com/nodeca/pica/blob/3.0.4/index.js#L278), this branch is used without ww.

**Comment by puzrin** [comment]
Close - no feedback.

@emrecamasuvi, create separate issue with more details is needed.
