### ISSUE TITLE
IE11 polyfills dont work

### ISSUE THREAD

**Issue by emrecamasuvi** [nodeca/pica#93]
Hi,
I've added many many "promise" polyfills for IE 11 but result is the same;
SCRIPT0: 'Promise' undefined

Same error on this page too: http://nodeca.github.io/pica/demo/ 

Any advice?

windows 10
IE Version: 11.0.15063.0
Update Versions: 11.0.40

**Comment by puzrin** [comment]
Hm. Should work. I use linux and have no IE11 to check right now.

Probably i've used wrong url in demo. Could you change in html `https://cdnjs.cloudflare.com/ajax/libs/lie/3.1.1/lie.min.js` to `https://cdnjs.cloudflare.com/ajax/libs/lie/3.1.1/lie.polyfill.min.js`?

Just download project edit [this](https://github.com/nodeca/pica/blob/master/demo/index.html#L9) line and open locally.

**Comment by puzrin** [comment]
Should not be problem with webworkes, because IE11 don't support those from data urls. But, for sure - disable those in demo.

**Comment by emrecamasuvi** [comment]
Hey Puzrin,
I think we made a mistake initiating Pica with wrong parameter.
`window.pica({ features: ["all"] });`
Instead of:
`window.pica({ features: ["js", "wasm"] });`

Thank you for your time.
Best!

**Comment by Pragmateek** [comment]
Indeed with IE11 Pica is not working with the default settings, you have to specify `{ features: ["js", "wasm"] }`.
Fair enough, but I was wondering what are the consequences of using these settings compared to the default ones?

**Comment by puzrin** [comment]
@Pragmateek did you tested with latest 3.0.5? It should fix that problem.

**Comment by Pragmateek** [comment]
Hello Vitaly,
indeed I'm using 3.0.4.
I'll test with 3.0.5 and keep you posted.

**Comment by Pragmateek** [comment]
With 3.0.5 the issue seems to be gone.
Thanks.
