### ISSUE TITLE
Preserve metadata

### ISSUE THREAD

**Issue by renchap** [nodeca/pica#94]
Hi,

First of all, thanks a lot for this library!

Usecase: I want to resize images in the browser before uploading them to reduce the time to upload big images (for example, when they directly come from a camera). I need to preserve any metadata in the original file.

As pointed in the README, I am considering re-using your `filter_jpeg` function from `nodeca`, but I am wondering if you would consider adding this feature directly to Pica?
Or maybe release a companion JS package with additional higher level features, like resizing and filtering metadata (so we can keep some, or all), or using the EXIF metadata to produce a canvas with correct orientation?

**Comment by puzrin** [comment]
Pica does not knows anything about image formats. It works with "pixel bitmaps". More high level things are out of this library scope.

It's not mandatory requirement to hack jpeg headers. Just a recommendation that can be useful, depending on your goals.

**Comment by puzrin** [comment]
In other words:

1. Metadata transforms should be in separate package. That will be a right design.
2. Due resource constrains, i can't create one more project without clear motivation (existing code is ok for my needs). If someone has enougth time and big image base for testing - feel free to reuse code, i'll be happy to help.
