### ISSUE TITLE
Include a gated Promise polyfill in web worker script

### ISSUE THREAD

**Issue by AndrewIngram** [nodeca/pica#96]
I have a frustrating browser-support edge case, the cause seems to be that IE11 supports web workers, but not Promises. It looks like polyfills applied outside of a worker aren't available inside (which makes sense), but pica makes heavy use of promises, and so fails to work in IE11 unless I explicitly disable web workers (which isn't ideal, because they're the key to acceptable performance).

Size of the polyfill might be an issue, [promise-polyfill](https://github.com/taylorhakes/promise-polyfill) comes in at around 6kb pre-minification.

**Comment by puzrin** [comment]
You are right. In this case code will fail. I think adding polyfill for such case is too much - it's possible to avoid promise use (or disable WW).

Could you tell me IE/OS version? IE11 has known bugs, failing to run WW from data url. It would be interesting to know why it works in your case.

**Comment by AndrewIngram** [comment]
It's IE11 on Windows 10, it's just a VM I got from modern.ie (specifically IE 11.0.10240.17394).

My environment (outside of the worker) is fully polyfilled using the results of polyfill-service (or polyfill.io).

If it's indeed the case that fixing the promise issue still won't fix web workers in IE11, i'm better off just dropping support for IE11 entirely, the non-WW performance is so bad (10s of seconds) as to be unusable.

Loving the WASM performance in modern browsers thought!

**Comment by puzrin** [comment]
Look at this https://github.com/nodeca/pica/blob/3.0.4/index.js#L132-L133. I don't know if this bug was fixed, but i guess it was not :). So, if it happens only in emulated IE (not in real IE), then bug exists but with lower priority.

**Comment by GlobalEffect** [comment]
Demo does not work. - http://nodeca.github.io/pica/demo/

Promise is undefined
Windows10, IE11 and Windows7, IE11

**Comment by puzrin** [comment]
Should be fixed in 3.0.5
