### ISSUE TITLE
"Cover" a.k.a. "Zoom to fit" to fill the canvas

### ISSUE THREAD

**Issue by Pragmateek** [nodeca/pica#97]
Hello,

first thanks for this great library, it has allowed me to fix a performance issue with previewing of "high-quality" images. :-)

My issue is that the `canvas` used to render the resized images are squared but the images are not, they can have any ratio.
So the resized images are "distorted".

In CSS the issue is solved by using `object-fit: cover`.
The image is "zoomed in" so that it fills the container, cropping the left and right sides if it is landscape-oriented, or cropping the top and bottom sides if portrait-oriented.

Is this behavior implemented in Pica?
If not how could I reproduce it?

I was thinking of computing the "zoomed in" size of the canvas:
- if in landscape-mode its width would be adjusted by the ratio: `canvasWidth = containerWidth * ratio`,
- if in portrait-mode its height would be adjusted.

And finally to crop the now overflowing sides set `overflow: hidden` on the parent.
Not perfectly sure it would work but anyway I'd prefer a built-in solution.

Thanks for any input. :-)

Mickael

**Comment by puzrin** [comment]
Pica does not crop, it rescale only. You should do additional operations externally. For example, via `.drawImage()`

https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/drawImage

**Comment by Pragmateek** [comment]
Thanks for the quick answer Vitaly.
Thanks for the feedback and the reference, I take good note of them.

I've finally done it "manually":

    const ratio = img.width / img.height;

    // Initially squared canvas
    imageCanvas.width = imageCanvasContainer.clientWidth;
    imageCanvas.height = imageCanvasContainer.clientHeight;

    if (ratio > 1) {
        imageCanvas.width *= ratio;
        // Horizontal offset to see the image's center
        imageCanvas.style.marginLeft = -(imageCanvas.width - imageCanvasContainer.clientWidth) / 2 + "px";
    }
    else if (ratio < 1) {
        imageCanvas.height /= ratio;
        // Vertical offset to see the image's center
        imageCanvas.style.marginTop = -(imageCanvas.height - imageCanvasContainer.clientHeight) / 2 + "px";
    }
