### ISSUE TITLE
android : brightness decrease

### ISSUE THREAD

**Issue by louisatome** [nodeca/pica#98]
When I use pica to resize my image on android, the resulted image is less bright than the original.

See fiddle : https://jsfiddle.net/0f40ppg6/2/

Tested with Google Chrome on android 5.1.1 and android 6.0.1

**Comment by puzrin** [comment]
I can not reproduce in android 7.0. Did you tried to disable `alpha`?

**Comment by louisatome** [comment]
I've tried to disable the alpha but the result is the same.
That's what I've got : http://imgur.com/DyRX1UM

I don't have an android 7 device so I can't check on this version.

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/master/test/brightness.js pica has tests to make sure math is correct.

I think that's a specific bug in canvas. Not sure this can be fixed.

**Comment by louisatome** [comment]
I think it should be somehow linked to pica because if I draw my image in the canvas without using pica, the rendering is correct.

**Comment by puzrin** [comment]
Could you clarify? Everything is ok if source is canvas but dark if source is image?

**Comment by louisatome** [comment]
Sorry. No i meant that if I draw my image in a canvas without using pica to resize it, the brightness is OK.

**Comment by puzrin** [comment]
That doesn't mean anything. Pica use different methods to extract bitmap data and put it back. Probably, color profile loss happen somewhere. But i have no device to investigate this effect.

**Comment by photopea** [comment]
I also think this has something to do with color profiles. I guess Pica expects everything to be in sRGB and ignores an attached color profile.

**Comment by puzrin** [comment]
Pica does not know anything about profiles. If works with canvas's 24-bit bitmap. There are no place for profile there.

**Comment by puzrin** [comment]
Is this still issue or can be closed?

**Comment by puzrin** [comment]
Close - outdated.
