### ISSUE TITLE
How to place an image not on the whole canvas?

### ISSUE THREAD

**Issue by nikitos-one** [nodeca/pica#99]
How to place an image not on the whole canvas?
like here: 
context.drawImage(image, 0, 0, **image.width * scale**, **image.height * scale**);

**Comment by puzrin** [comment]
Resize, then draw from result to required area https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/drawImage.

That's not related to this package.

**Comment by nikitos-one** [comment]
Я так понимаю Вы из Санкт-Петербурга, не будет наглостью попросить у Вас
совета, чем можно уменьшить картинку png используя JS при этом не потерять
качество, и в дальнейшем использовать ее для drawImage в canvas. Я уже
голову сломал над этим вопросом

2017-07-05 18:13 GMT+03:00 Vitaly Puzrin <notifications@github.com>:

**Comment by puzrin** [comment]
Please, use english in public trackers.

Can't help with PNG. This package use `Image` and `Canvas` as input data. I can answer questions only about this package.

**Comment by nikitos-one** [comment]
I'm sorry, you will not have a working example .resizeBuffer method?

2017-07-05 21:52 GMT+03:00 Vitaly Puzrin <notifications@github.com>:

**Comment by puzrin** [comment]
https://github.com/nodeca/pica/blob/3.0.5/test/fixture_resize.js#L114
